package main

// emit_mbt.go：.json.mbt 真源 emit + round-trip 对拍（铺开批 2026-10-07）。
// lexer digest = sources（corpus→{name:sha8} 双层）+ tsvs（平铺 name→sha16）。

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"vitro/scripts/jmemit"
)

const lexDigestMbt = "scripts/lexer_diff/golden_digest.json.mbt"

func emitLexMbt(p string, d lexDigestDoc) {
	raw, err := os.ReadFile(p)
	if err != nil {
		fmt.Fprintf(os.Stderr, "emit: 读 %s: %v\n", p, err)
		os.Exit(1)
	}
	corpusNames := lSortedKeys(d.Sources)
	secs := []jmemit.FlatSection{}
	for _, cname := range corpusNames {
		m := d.Sources[cname]
		ord := jmemit.KeyOrderOfScalars(raw, cname)
		if len(ord) != len(m) {
			ord = lSortedKeys(m)
		}
		secs = append(secs, jmemit.FlatSection{
			Name: cname, Sources: m, SrcOrder: ord,
			Hashes: map[string]string{}, HashOrder: nil,
		})
	}
	// tsvs 平铺层：单节承载（hashes 槽）
	tsvOrd := jmemit.KeyOrderOfScalars(raw, "tsvs")
	if len(tsvOrd) != len(d.TSVs) {
		tsvOrd = lSortedKeys(d.TSVs)
	}
	jmemit.EmitAndVerify(lexDigestMbt, raw, func(_ map[string][]string) string {
		var b strings.Builder
		w := func(s string) { b.WriteString(s + "\n") }
		w("// @generated by lexer_diff freeze (scripts/jmemit) —— 禁手改（再生成：freeze 循环）。")
		w("pub struct Section {")
		w("  sources : Map[String, String]")
		w("  hashes : Map[String, String]")
		w("}")
		w("")
		w("pub struct Digest {")
		w("  version : Int")
		w("  tsvs : Map[String, String]")
		w("  sections : Map[String, Section]")
		w("}")
		w("")
		w("pub let golden_digest : Digest = Digest::{")
		fmt.Fprintf(&b, "  version: %d,\n", d.Version)
		w("  tsvs: {")
		for _, n := range tsvOrd {
			fmt.Fprintf(&b, "    %s: %s,\n", jmemit.Quote(n), jmemit.Quote(d.TSVs[n]))
		}
		w("  },")
		w("  sections: {")
		for _, sec := range secs {
			fmt.Fprintf(&b, "    %s: Section::{\n", jmemit.Quote(sec.Name))
			w("      sources: {")
			for _, n := range sec.SrcOrder {
				fmt.Fprintf(&b, "        %s: %s,\n", jmemit.Quote(n), jmemit.Quote(sec.Sources[n]))
			}
			w("      },")
			w("      hashes: {},")
			w("    },")
		}
		w("  },")
		w("}")
		return b.String()
	}, func(regen []byte) int {
		var rd struct {
			Version  int               `json:"version"`
			Tsvs     map[string]string `json:"tsvs"`
			Sections map[string]struct {
				Sources map[string]string `json:"sources"`
			} `json:"sections"`
		}
		if err := json.Unmarshal(regen, &rd); err != nil {
			fmt.Fprintf(os.Stderr, "emit: 再生件解析失败: %v\n", err)
			return 1
		}
		bad := 0
		if !lMapsEqual(d.TSVs, rd.Tsvs) {
			fmt.Fprintf(os.Stderr, "emit: tsvs 漂移\n")
			bad++
		}
		for cname, m := range d.Sources {
			r, ok := rd.Sections[cname]
			if !ok {
				fmt.Fprintf(os.Stderr, "emit: 丢节 %s\n", cname)
				bad++
				continue
			}
			if !lMapsEqual(m, r.Sources) {
				fmt.Fprintf(os.Stderr, "emit: 漂移节 %s\n", cname)
				bad++
			}
		}
		if len(rd.Sections) != len(d.Sources) {
			bad++
		}
		return bad
	})
}

func lSortedKeys[T any](m map[string]T) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func lMapsEqual(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if b[k] != v {
			return false
		}
	}
	return true
}
