// gen_host_route：S5 host 路由表生成器（gen_diag 同构模式）。
//
// 用法（cd moonbit）：
//
//	go run ./scripts/gen_host_route          # 生成产物（写盘 + moon fmt）
//	go run ./scripts/gen_host_route -check   # 幂等校验（产物漂移即红）
//
// 产物（codegen/ 包）：
//   - host_func_id_gen.mbt        ：110 常量 + PURE 表 + by_user_name 逐对
//   - host_route_anchor_wbtest.mbt：110 对硬编码锚（独立文件——实现漂移即红）
//
// 源：../native/crates/vitro_runtime/src/host_func_id.rs（冻结区，只读）。
// 源 sha256 前 8 位落款进产物头；源变须重新生成（-check 在 CI/审阅防漂移）。
//
// 幂等：同源重复运行产物字节一致（无时间戳）；行尾归一后取 sha（LF/CRLF
// 工作树形态不影响产物落款——gen_diag 同款双保险）。
//
// 2026-09-21 审阅修复（P2a）：此前 host_func_id_gen.mbt 头部声称"脚本生成
// 禁手改"但无脚本/无 -check/无落款——"假生成物"，再生成义务无机制保证。
// 本生成器补齐三件套，首跑 -check 对手抄旧产物必红（由红转绿留痕）。
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	expectedConsts = 110
	expectedPairs  = 110
	expectedPure   = 14
)

var constRe = regexp.MustCompile(`pub const ([A-Z][A-Z0-9_]+): u32 = (\d+);`)
var armRe = regexp.MustCompile(`((?:"[a-zA-Z_][a-zA-Z0-9_]*"(?:\s*\|\s*)?)+)\s*=>\s*Some\(([A-Z][A-Z0-9_]+)\)`)
var nameRe = regexp.MustCompile(`"([a-zA-Z_][a-zA-Z0-9_]*)"`)
var pureBlockRe = regexp.MustCompile(`BYTECODE_LIBC_PURE_FUNCS[^=]*=\s*&\[([^]]+)\]`)

func main() {
	if err := os.Chdir("moonbit"); err != nil {
		fmt.Fprintf(os.Stderr, "chdir moonbit failed: %v", err)
		os.Exit(2)
	}

	check := flag.Bool("check", false, "只校验产物未漂移，不写入")
	srcPath := flag.String("src", "../native/crates/vitro_runtime/src/host_func_id.rs", "host_func_id.rs 路径")
	outDir := flag.String("out", "codegen", "输出目录")
	flag.Parse()

	src, err := os.ReadFile(*srcPath)
	if err != nil {
		fatalf("读源失败 %s: %v", *srcPath, err)
	}
	src = bytes.ReplaceAll(src, []byte("\r\n"), []byte("\n"))
	srcHash := fmt.Sprintf("%x", sha256.Sum256(src))[:8]

	// —— 解析（与锚相同的三个抽取面）——
	consts := [][2]string{} // (NAME, "value")
	constVals := map[string]string{}
	for _, m := range constRe.FindAllStringSubmatch(string(src), -1) {
		consts = append(consts, [2]string{m[1], m[2]})
		constVals[m[1]] = m[2]
	}
	if len(consts) != expectedConsts {
		fatalf("常量数 %d ≠ 基线 %d——源已变更，请人工核对后更新 expectedConsts 并登记差异", len(consts), expectedConsts)
	}
	pairs := [][2]string{} // (user_name, CONST)
	for _, m := range armRe.FindAllStringSubmatch(string(src), -1) {
		for _, n := range nameRe.FindAllStringSubmatch(m[1], -1) {
			pairs = append(pairs, [2]string{n[1], m[2]})
		}
	}
	if len(pairs) != expectedPairs {
		fatalf("名→常量对数 %d ≠ 基线 %d——源已变更，请人工核对后更新 expectedPairs 并登记差异", len(pairs), expectedPairs)
	}
	for _, p := range pairs {
		if _, ok := constVals[p[1]]; !ok {
			fatalf("match 臂引用未定义常量 %s", p[1])
		}
	}
	pureBlock := pureBlockRe.FindStringSubmatch(string(src))
	if pureBlock == nil {
		fatalf("PURE 表未找到")
	}
	pure := nameRe.FindAllStringSubmatch(pureBlock[1], -1)
	if len(pure) != expectedPure {
		fatalf("PURE 名数 %d ≠ 基线 %d——源已变更，请人工核对后更新 expectedPure 并登记差异", len(pure), expectedPure)
	}
	pureSet := map[string]bool{}
	for _, m := range pure {
		pureSet[m[1]] = true
	}

	genImpl := renderImpl(consts, pairs, pure, srcHash)
	genAnchor := renderAnchor(pairs, pureSet, constVals, srcHash)

	writeProducts(*outDir, map[string]string{
		"host_func_id_gen.mbt":         genImpl,
		"host_route_anchor_wbtest.mbt": genAnchor,
	}, *check)

	if *check {
		fmt.Println("gen_host_route: check OK（产物与源一致，未漂移）")
	}
}

// renderImpl 生成实现文件（行宽控制在 80 列内——moon fmt 宽度按 UTF-8
// 字节计，超宽会爆开与 gen 互踩；本文件全部短行，无 wrap 需要）。
func renderImpl(consts [][2]string, pairs [][2]string, pure [][]string, srcHash string) string {
	var b strings.Builder
	w := func(s string) { b.WriteString(s + "\n") }
	w("///|")
	w("// AUTO-GENERATED by scripts/gen_host_route（Go，2026-09-21）——禁手改。")
	w("// 源：native/crates/vitro_runtime/src/host_func_id.rs（sha256/" + srcHash + "，行尾归一）")
	w("// 再生成：cd moonbit && go run ./scripts/gen_host_route（-check 幂等校验）")
	w("//")
	w("// Host 函数路由（S5 扩展批·gen_call_ptr 依赖）——Rust")
	w("// `vitro_runtime::host_func_id` 的照搬：110 常量 + PURE 表 +")
	w("// by_user_name 逐对。语义：Bytecode Libc 已覆盖的纯计算函数返回")
	w("// None（生成固定索引 Call 而非 CallHost）；诊断敏感函数（printf/")
	w("// malloc/strcpy 等）返回 host id 走 CallHost。")
	w("//")
	w("// **S6 上提预告**：host 路由表语义属 L7 `vitro/engine/host` 包（110")
	w("// 路由表单源），本表暂居 codegen 包（S5 发射侧唯一消费点）；S6 建包")
	w("// 时整体上提，codegen 改 import——登记于总计划 S5/S6 行。")
	for _, c := range consts {
		w("const HOST_" + c[0] + " : Int = " + c[1])
	}
	w("")
	w("///|")
	w("/// Bytecode Libc 已覆盖的纯计算函数（返回 None 走固定索引 Call）。")
	w("let bytecode_libc_pure_funcs : Array[String] = [")
	var pureNames []string
	for _, p := range pure {
		pureNames = append(pureNames, "\""+p[1]+"\"")
	}
	w("    " + strings.Join(pureNames, ", "))
	w("]")
	w("")
	w("///|")
	w("fn is_bytecode_libc_pure(name : String) -> Bool {")
	w("    bytecode_libc_pure_funcs.contains(name)")
	w("}")
	w("")
	w("///|")
	w("/// 用户函数名 → host id（Rust `by_user_name` 逐对照搬；PURE 短路在")
	w("/// match 之前——PURE 名的 Some 臂不可达，由锚的 None 断言覆盖）。")
	w("fn host_func_id_by_user_name(name : String) -> Int? {")
	w("    if is_bytecode_libc_pure(name) {")
	w("        return None")
	w("    }")
	w("    match name {")
	for _, p := range pairs {
		w("        \"" + p[0] + "\" => Some(HOST_" + p[1] + ")")
	}
	w("        _ => None")
	w("    }")
	w("}")
	return b.String()
}

// renderAnchor 生成硬编码锚（独立文件：实现再生成/漂移与锚不同步即红；
// PURE 名在 Rust 语义中被短路为 None，不出现在 Some 断言——注释保留
// 名单可见性）。
func renderAnchor(pairs [][2]string, pureSet map[string]bool, constVals map[string]string, srcHash string) string {
	var b strings.Builder
	w := func(s string) { b.WriteString(s + "\n") }
	w("///|")
	w("// AUTO-GENERATED by scripts/gen_host_route——禁手改。")
	w("// 源：native/crates/vitro_runtime/src/host_func_id.rs（sha256/" + srcHash + "，行尾归一）")
	w("//")
	w("// Host 路由硬编码对拍锚：110 对逐条断言 Some(id) + 14 PURE 名断言")
	w("// None（Rust 语义：PURE 短路在 match 之前，match 臂的 Some 值不可达）。")
	w("// 实现文件由同一生成器产出但为独立文件——实现手改/漂移与锚不同步即红。")
	w("test \"host route: hardcoded pairs from Rust source\" {")
	w("    let pairs : Array[(String, Int)] = [")
	for _, p := range pairs {
		if pureSet[p[0]] {
			continue
		}
		w("        (\"" + p[0] + "\", " + constVals[p[1]] + "),")
	}
	w("    ]")
	w("    for pair in pairs {")
	w("        assert_eq(host_func_id_by_user_name(pair.0), Some(pair.1))")
	w("    }")
	w("    // PURE 名走 bytecode libc（host id 为 None——短路在 match 之前）")
	w("    for pure_name in bytecode_libc_pure_funcs {")
	w("        assert_true(host_func_id_by_user_name(pure_name) is None)")
	w("    }")
	w("    // 非内置名 None")
	w("    assert_true(host_func_id_by_user_name(\"main\") is None)")
	w("    assert_true(host_func_id_by_user_name(\"my_func\") is None)")
	w("}")
	return b.String()
}

// writeProducts 写出全部产物并经 moon fmt 规范化（gen_diag 同构：gen 与
// fmt 不得互踩，最终形态一律以 moon fmt 输出为准；check 模式行尾归一后
// 逐字节比对，不一致还原并红——check 不留副作用）。
func writeProducts(dir string, products map[string]string, check bool) {
	type item struct {
		path string
		cur  []byte
	}
	var items []item
	paths := make([]string, 0, len(products))
	for name := range products {
		paths = append(paths, name)
	}
	sort.Strings(paths)
	for _, name := range paths {
		path := filepath.Join(dir, name)
		var cur []byte
		if check {
			var err error
			cur, err = os.ReadFile(path)
			if err != nil {
				fatalf("-check: 读产物失败 %s: %v", path, err)
			}
		}
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fatalf("建目录失败 %s: %v", dir, err)
		}
		if err := os.WriteFile(path, []byte(products[name]), 0o644); err != nil {
			fatalf("写产物失败 %s: %v", path, err)
		}
		items = append(items, item{path, cur})
	}
	args := []string{"fmt"}
	for _, it := range items {
		args = append(args, it.path)
	}
	if out, err := runMoon(args...); err != nil {
		for _, it := range items {
			if len(it.cur) > 0 {
				_ = os.WriteFile(it.path, it.cur, 0o644)
			}
		}
		fatalf("moon fmt 失败（moon 须在 PATH）: %v\n%s", err, out)
	}
	if !check {
		return
	}
	for _, it := range items {
		now, err := os.ReadFile(it.path)
		if err != nil {
			fatalf("-check: 回读产物失败 %s: %v", it.path, err)
		}
		nowLF := bytes.ReplaceAll(now, []byte{13, 10}, []byte{10})
		curLF := bytes.ReplaceAll(it.cur, []byte{13, 10}, []byte{10})
		if !bytes.Equal(nowLF, curLF) {
			if werr := os.WriteFile(it.path, it.cur, 0o644); werr != nil {
				fatalf("-check: 还原产物失败 %s: %v", it.path, werr)
			}
			fatalf("-check: 产物漂移 %s——源已变更未再生成（cd moonbit && go run ./scripts/gen_host_route）", it.path)
		}
	}
}

func runMoon(args ...string) (string, error) {
	cmd := exec.Command("moon", args...)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	err := cmd.Run()
	return out.String(), err
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen_host_route: "+format+"\n", args...)
	os.Exit(2)
}
