double sin(double x);
double cos(double x);
double tan(double x);
double sqrt(double x);
double pow(double x, double y);
double atan(double x);
double log(double x);
double log10(double x);
double exp(double x);
double fabs(double x);
double ceil(double x);
double floor(double x);
double round(double x);
double fmod(double x, double y);
double asin(double x);
double acos(double x);
double atan2(double y, double x);
double sinh(double x);
double cosh(double x);
double tanh(double x);
