typedef unsigned int size_t;
typedef void* FILE;

int printf(const char* fmt);
int scanf(const char* fmt);
int sprintf(char* buf, const char* fmt);
int snprintf(char* buf, int size, const char* fmt);
int sscanf(const char* str, const char* fmt);
int fprintf(FILE* stream, const char* fmt);
int getchar(void);
int putchar(int c);
int puts(const char* s);
FILE* fopen(const char* path, const char* mode);
int fclose(FILE* stream);
int fread(void* ptr, int size, int nmemb, FILE* stream);
int fwrite(void* ptr, int size, int nmemb, FILE* stream);
int feof(FILE* stream);
char* fgets(char* s, int n, FILE* stream);
int fputs(const char* s, FILE* stream);
int ungetc(int c, FILE* stream);
int fgetc(FILE* stream);
int fputc(int c, FILE* stream);
int fseek(FILE* stream, int offset, int whence);
int ftell(FILE* stream);
void rewind(FILE* stream);
int fflush(FILE* stream);
void perror(const char* s);
void clearerr(FILE* stream);
int remove(const char* pathname);
int rename(const char* oldpath, const char* newpath);
