typedef unsigned int size_t;

void* malloc(int size);
void* calloc(int nmemb, int size);
void free(void* ptr);
void* realloc(void* ptr, int size);
int atoi(const char* s);
double atof(const char* s);
long long atol(const char* s);
int abs(int n);
int rand(void);
void srand(int seed);
void qsort(void* base, int nmemb, int size, int (*compar)(const void*, const void*));
void* bsearch(const void* key, const void* base, int nmemb, int size, int (*compar)(const void*, const void*));
void exit(int status);
void abort(void);
long long strtol(const char* str, char** endptr, int base);
double strtod(const char* str, char** endptr);
long long llabs(long long n);
long long llabs(long long n);
