typedef unsigned int size_t;

int strlen(const char* s);
char* strcpy(char* dest, const char* src);
char* strncpy(char* dest, const char* src, int n);
int strcmp(const char* s1, const char* s2);
int strncmp(const char* s1, const char* s2, int n);
char* strcat(char* dest, const char* src);
char* strncat(char* dest, const char* src, int n);
void* memcpy(void* dest, const void* src, int n);
void* memmove(void* dest, const void* src, int n);
void* memset(void* ptr, int value, int n);
int memcmp(const void* s1, const void* s2, int n);
char* strchr(const char* s, int c);
char* strrchr(const char* s, int c);
char* strstr(const char* haystack, const char* needle);
void* memchr(const void* s, int c, int n);
char* strdup(const char* s);
char* strerror(int errnum);
char* strpbrk(const char* s, const char* accept);
int strspn(const char* s, const char* accept);
int strcspn(const char* s, const char* reject);
