// gen_protocol_fields：S7 protocol 字段白名单生成器（gen_host_route 同构
// 模式，2026-09-27 用户审阅 P2-2 落地）。
//
// 用法（cd 仓库根）：
//
//	go run ./scripts/moonbit/gen_protocol_fields          # 生成产物（写盘 + moon fmt）
//	go run ./scripts/moonbit/gen_protocol_fields -check   # 幂等校验（产物漂移即红）
//
// 产物（protocol/ 包）：
//   - schema_fields_gen.mbt：step_payload_fields_v0_1() / reserved_fields_v0_2()
//     两函数（v0.1 十四字段白名单 + v0.2 预留位四条）
//
// 背景（审阅 P2-2）：此前 MoonBit 侧白名单为手写常量 + 白盒测试硬编码第二
// 份，与声称的「对账单源 scripts/replay/v01_payload_fields.json」零联动——
// 向 JSON 注入第 15 字段 ZZ_INJECTED_FIELD 实测 25/25 假绿（Rust 侧同样
// 硬编码，只有 Go replay 驱动真读文件）。本生成器把 JSON 变成 MoonBit 侧
// 的**生成期真单源**：源变（新增字段/重命名）→ 产物变 → -check 红 →
// 人工核对后重新生成。三层联动自此成立：
//
//	JSON ─(本生成器，生成期)→ schema_fields_gen.mbt ─(白盒硬编码锚，测试期)→ 语义
//	JSON ─(Go/Python replay 驱动，运行期)→ Rust serve 输出
//
// 源：../scripts/replay/v01_payload_fields.json（v0.1 冻结字段表；schema
// 激活 v0.2 时在该文件登记新字段后重新生成——v0_2_activation_checklist ②）。
// 源 sha256 前 8 位落款进产物头；幂等：同源重复运行产物字节一致（行尾
// 归一后取 sha，LF/CRLF 工作树不影响落款——gen_host_route 同款双保险）。
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	expectedV01    = 14
	expectedRes    = 4
	expectedSchema = "v0.1"
)

type fieldsFile struct {
	Schema           string   `json:"schema"`
	V01PayloadFields []string `json:"v01_payload_fields"`
	ReservedFields   []string `json:"reserved_fields"`
}

func main() {
	if err := os.Chdir("moonbit"); err != nil {
		fatalf("chdir moonbit failed: %v", err)
	}
	check := flag.Bool("check", false, "只校验产物未漂移，不写入")
	srcPath := flag.String("src", "../scripts/replay/v01_payload_fields.json", "字段白名单 JSON 路径")
	outDir := flag.String("out", "protocol", "输出目录")
	flag.Parse()

	src, err := os.ReadFile(*srcPath)
	if err != nil {
		fatalf("读源失败 %s: %v", *srcPath, err)
	}
	srcLF := bytes.ReplaceAll(src, []byte("\r\n"), []byte("\n"))
	srcHash := fmt.Sprintf("%x", sha256.Sum256(srcLF))[:8]

	var f fieldsFile
	if err := json.Unmarshal(srcLF, &f); err != nil {
		fatalf("解析 JSON 失败: %v", err)
	}
	if f.Schema != expectedSchema {
		fatalf("schema %q ≠ %q——版本轨道变更，须人工评估（v0_2_activation_checklist 全流程）", f.Schema, expectedSchema)
	}
	if len(f.V01PayloadFields) != expectedV01 {
		fatalf("v01_payload_fields 数 %d ≠ 基线 %d——源已变更：字段表只增不改，请人工核对后更新 expectedV01 并登记（v0.2 激活走 checklist）", len(f.V01PayloadFields), expectedV01)
	}
	if len(f.ReservedFields) != expectedRes {
		fatalf("reserved_fields 数 %d ≠ 基线 %d——源已变更，请人工核对后更新 expectedRes", len(f.ReservedFields), expectedRes)
	}
	// 白名单自身查重（重复字段 = 单源内部矛盾，生成期拒绝）
	seen := map[string]bool{}
	for _, name := range append(append([]string{}, f.V01PayloadFields...), f.ReservedFields...) {
		if seen[name] {
			fatalf("字段 %q 在白名单内重复", name)
		}
		seen[name] = true
	}

	gen := render(f, srcHash)
	writeProduct(filepath.Join(*outDir, "schema_fields_gen.mbt"), gen, *check)
	if *check {
		fmt.Println("gen_protocol_fields: check OK（产物与 JSON 单源一致，未漂移）")
	}
}

func render(f fieldsFile, srcHash string) string {
	var b strings.Builder
	w := func(s string) { b.WriteString(s + "\n") }
	w("// @generated by scripts/moonbit/gen_protocol_fields —— 禁手改（git/diff 工具链按 @generated 识别；再生成：仓库根 go run ./scripts/moonbit/gen_protocol_fields）。")
	w("// 源：scripts/replay/v01_payload_fields.json（sha256/" + srcHash + "，行尾归一）")
	w("// 再生成：cd 仓库根 && go run ./scripts/moonbit/gen_protocol_fields（-check 幂等校验；CI 接线防漂移）")
	w("//")
	w("// StepPayload v0.1 字段白名单（生成期真单源——2026-09-27 用户审阅")
	w("// P2-2 落地：此前手写常量与 JSON 零联动，注入实验实锤假绿）。JSON")
	w("// 侧消费方：Go/Python replay 驱动（S5 断言判据）；本产物消费方：")
	w("// gateway serve 批键集合冻结断言 + schema_wbtest 硬编码第三份锚。")
	w("")
	w("///| StepPayload v0.1 顶层字段白名单（14 字段，顺序 = schema §字段表）。")
	w("///| 单源 = scripts/replay/v01_payload_fields.json（本文件为其生成物）。")
	w("pub fn step_payload_fields_v0_1() -> Array[String] {")
	w("  [")
	line := "   "
	for i, name := range f.V01PayloadFields {
		item := "\"" + name + "\","
		if i%4 == 0 && i > 0 {
			w(line)
			line = "   "
		}
		line += " " + item
	}
	w(line)
	w("  ]")
	w("}")
	w("")
	w("///| v0.2 预留位字段（异常域，激活前不得出现在任何 payload 中）。")
	w("///| 单源 = v01_payload_fields.json 的 reserved_fields（本文件为其生成物）。")
	w("pub fn reserved_fields_v0_2() -> Array[String] {")
	w("  [" + strings.Join(quoteAll(f.ReservedFields), ",") + "]")
	w("}")
	return b.String()
}

func quoteAll(items []string) []string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "\"" + s + "\""
	}
	return out
}

type item struct {
	path string
	cur  []byte
}

func writeProduct(path, gen string, check bool) {
	items := []item{{path: path}}
	if cur, err := os.ReadFile(path); err == nil {
		items[0].cur = cur
	}
	if err := os.WriteFile(path, []byte(gen), 0o644); err != nil {
		if check {
			restoreItems(items)
		}
		fatalf("写产物失败 %s: %v", path, err)
	}
	if out, err := runMoon("fmt", path); err != nil {
		restoreItems(items)
		fatalf("moon fmt 失败（moon 须在 PATH）: %v\n%s", err, out)
	}
	if !check {
		return
	}
	// 全部 fmt 完成后统一比对（check 不留副作用契约——gen_host_route 同款）
	now, err := os.ReadFile(path)
	if err != nil {
		restoreItems(items)
		fatalf("-check: 回读产物失败 %s: %v", path, err)
	}
	nowLF := bytes.ReplaceAll(now, []byte{13, 10}, []byte{10})
	curLF := bytes.ReplaceAll(items[0].cur, []byte{13, 10}, []byte{10})
	if !bytes.Equal(nowLF, curLF) {
		restoreItems(items)
		fatalf("-check: 产物漂移 %s——JSON 单源已变更未再生成（cd 仓库根 && go run ./scripts/moonbit/gen_protocol_fields）", path)
	}
}

func restoreItems(items []item) {
	for _, it := range items {
		if len(it.cur) > 0 {
			_ = os.WriteFile(it.path, it.cur, 0o644)
		}
	}
}

func runMoon(args ...string) (string, error) {
	cmd := exec.Command("moon", args...)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	err := cmd.Run()
	return out.String(), err
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen_protocol_fields: "+format+"\n", args...)
	os.Exit(2)
}
