// gen_stubs：从 Rust oracle 的 14 个标准库存根（native/runtime_libc/include/*.h）
// 生成 MoonBit 数据表 moonbit/lexer/internal/host/stubs_gen.mbt。
//
// 纪律（沿 moonbit/scripts/gen_diag 先例）：
//   - 禁手抄：产物唯一来源 = native/runtime_libc/include/*.h（冻结区资产）；
//   - 幂等：双次运行字节一致；行尾规范化（LF）后取源 sha256 落款；
//   - --check：产物与源不一致即 exit 1（fail loud）；
//   - 用法：go run ./scripts/moonbit/gen_stubs [--check]（仓库根运行）
package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
)

// 与 Rust resolver.rs load_stub 的 match 顺序一致
var stubNames = []string{
	"stdio.h", "stdlib.h", "ctype.h", "math.h", "string.h", "stdarg.h",
	"limits.h", "stdbool.h", "stddef.h", "stdint.h", "time.h",
	"assert.h", "errno.h", "float.h",
}

const sourceRoot = "native/runtime_libc/include"
const outFile = "moonbit/lexer/internal/host/stubs_gen.mbt"

func moonEscape(s string) string {
	var b bytes.Buffer
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		default:
			if r < 0x20 {
				fmt.Fprintf(os.Stderr, "gen_stubs: 控制字符 U+%04X 出现在存根中，需人工裁定转义口径\n", r)
				os.Exit(1)
			}
			// 非 ASCII（存根含中文注释/em dash）直出——MoonBit 源码与字符串均为 UTF-8
			b.WriteRune(r)
		}
	}
	return b.String()
}

func main() {
	// （迁址自 moonbit/scripts/ 但**不 chdir**——本脚本原设计即仓库根
	// 运行：sourceRoot=native/... 无 ../ 前缀、go.mod 自检查仓库根）

	if _, err := os.Stat("go.mod"); err != nil {
		fmt.Fprintln(os.Stderr, "gen_stubs: 必须在仓库根目录运行（找不到 go.mod）")
		os.Exit(1)
	}
	var digestInput bytes.Buffer
	var matchArms bytes.Buffer
	for _, name := range stubNames {
		raw, err := os.ReadFile(filepath.Join(sourceRoot, name))
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen_stubs: 读取存根失败 %s: %v\n", name, err)
			os.Exit(1)
		}
		normalized := bytes.ReplaceAll(raw, []byte("\r\n"), []byte("\n"))
		digestInput.Write(normalized)
		// 已转义文本禁用 %q（会二次转义：`\n` 两字符被 %q 变成 "\\n"——
		// MoonBit 源里即字面反斜杠+n，曾致存根全部挤成一行 + 30 条 E1001）
		matchArms.WriteString(fmt.Sprintf("    \"%s\" => Some(\"%s\")\n", name, moonEscape(string(normalized))))
	}
	sum := sha256.Sum256(digestInput.Bytes())
	var out bytes.Buffer
	out.WriteString("// Generated by moonbit/scripts/gen_stubs from native/runtime_libc/include/*.h — DO NOT EDIT\n")
	out.WriteString(fmt.Sprintf("// source sha256: %x（14 存根规范化行尾后按固定顺序拼接）\n", sum))
	out.WriteString("\n///|\n")
	out.WriteString("/// 标准库存根内容表（14 个；内容唯一来源 = Rust oracle 冻结资产，本文件为生成物）。\n")
	out.WriteString("pub fn stub_lookup(name : String) -> String? {\n")
	out.WriteString("  match name {\n")
	out.Write(matchArms.Bytes())
	out.WriteString("    _ => None\n")
	out.WriteString("  }\n")
	out.WriteString("}\n")

	existing, readErr := os.ReadFile(outFile)
	if readErr == nil && bytes.Equal(bytes.ReplaceAll(existing, []byte("\r\n"), []byte("\n")), out.Bytes()) {
		fmt.Printf("gen_stubs: 产物与源一致（sha256 %x）\n", sum)
		return
	}
	if len(os.Args) > 1 && os.Args[1] == "--check" {
		fmt.Fprintln(os.Stderr, "gen_stubs: --check 失败——产物与 native 存根不一致，请重新生成（go run ./moonbit/scripts/gen_stubs）")
		os.Exit(1)
	}
	if err := os.WriteFile(outFile, out.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen_stubs: 写入失败: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("gen_stubs: 已生成 %s（sha256 %x）\n", outFile, sum)
}
