// gen_stubs：从 Rust oracle 的 14 个标准库存根（scripts/moonbit/libc_src/include/*.h（2026-10-05 迁出冻结区））
// 生成 MoonBit 数据表 moonbit/lexer/internal/host/stubs_gen.mbt。
//
// 纪律（沿 scripts/moonbit/gen_diag 先例）：
//   - 禁手抄：产物唯一来源 = scripts/moonbit/libc_src/include/*.h（2026-10-05 迁出冻结区）（冻结区资产）；
//   - 幂等：双次运行字节一致；行尾规范化（LF）后取源 sha256 落款；
//   - **生成流程内置 moon fmt**（陷阱 #15：产物形态以 fmt 为准，gen 原始输出
//     只是中间态）。2026-09-23 审阅批修复：此前无 fmt 且手工比对只认 --check——
//     仓库产物（fmt 形态）与生成输出（未 fmt）恒不等，--check 在干净仓库上
//     **必红**（无法入 CI），而 -check 单横线静默落入生成路径直接改写产物；
//   - -check / --check 经 flag 包解析（与 gen_diag / gen_host_route 口径统一）：
//     产物与源不一致即 exit 1（fail loud），check 不留副作用（漂移即还原原内容）；
//   - 用法：go run ./scripts/moonbit/gen_stubs [-check]（仓库根运行）
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// chdir moonbit/ 后的相对路径（moon fmt 是 workspace 命令，须自 workspace 根调用）
const sourceRoot = "../scripts/moonbit/libc_src/include"
const outFile = "lexer/internal/host/stubs_gen.mbt"

// 头文件名单唯一真源 = vitro/engine/stdlib 的 headers()（moonbit/stdlib/stdlib.mbt，
// 方案 A P1 批——设计稿《标准库单源与头文件多文件设计20261010》§3.6）。Go 不能
// import MoonBit 包，故按文本解析 headers() 的数组字面量（moon fmt 只动空白，引号串
// 稳定）；序 = Rust resolver.rs load_stub 的 match 序（历史序冻结，决定产物臂序与
// sha256 拼接序）。解析不到 / 空清单 / 非 .h 项一律 fail loud。
const stdlibSrc = "stdlib/stdlib.mbt"

func loadHeaderNames() []string {
	raw, err := os.ReadFile(stdlibSrc)
	if err != nil {
		fatalf("读取 stdlib 真源失败 %s: %v", stdlibSrc, err)
	}
	text := string(toLF(raw))
	fnAt := strings.Index(text, "pub fn headers() -> Array[String]")
	if fnAt < 0 {
		fatalf("stdlib 真源缺少 pub fn headers() -> Array[String]（形态变更须同步本解析器）")
	}
	// 锚定从签名之后起找——首个 [..] 对是签名泛型 Array[String]，不是数组体
	sigAt := strings.Index(text[fnAt:], "Array[String]")
	body := text[fnAt+sigAt+len("Array[String]"):]
	open := strings.Index(body, "[")
	close_ := strings.Index(body, "]")
	if open < 0 || close_ < open {
		fatalf("stdlib headers() 数组字面量缺失")
	}
	var names []string
	for _, m := range regexp.MustCompile(`"([^"\n]+)"`).FindAllStringSubmatch(body[open:close_], -1) {
		names = append(names, m[1])
	}
	if len(names) == 0 {
		fatalf("stdlib headers() 名单为空")
	}
	for _, n := range names {
		if !strings.HasSuffix(n, ".h") {
			fatalf("stdlib headers() 含非 .h 条目 %q", n)
		}
	}
	return names
}

// 名单 ↔ include 目录双向集合对账（headers 三方一致闸的 P1 版：目录多出未登记头 /
// 登记名无对应文件均红；第三面 = capabilities.libraries JSON 出口，P3 接线）。
func crossCheckDir(names []string) {
	entries, err := os.ReadDir(sourceRoot)
	if err != nil {
		fatalf("扫描存根目录失败 %s: %v", sourceRoot, err)
	}
	dirSet := map[string]bool{}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".h") {
			dirSet[e.Name()] = true
		}
	}
	nameSet := map[string]bool{}
	for _, n := range names {
		nameSet[n] = true
	}
	for n := range dirSet {
		if !nameSet[n] {
			fatalf("目录存在未登记头 %s（stdlib headers() 缺条目——加进 moonbit/stdlib/stdlib.mbt）", n)
		}
	}
	for n := range nameSet {
		if !dirSet[n] {
			fatalf("headers() 登记 %s 在目录中不存在（libc_src/include/）", n)
		}
	}
}

func toLF(b []byte) []byte {
	return bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
}

func moonEscape(s string) string {
	var b bytes.Buffer
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		default:
			if r < 0x20 {
				fmt.Fprintf(os.Stderr, "gen_stubs: 控制字符 U+%04X 出现在存根中，需人工裁定转义口径\n", r)
				os.Exit(1)
			}
			// 非 ASCII（存根含中文注释/em dash）直出——MoonBit 源码与字符串均为 UTF-8
			b.WriteRune(r)
		}
	}
	return b.String()
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen_stubs: "+format+"\n", args...)
	os.Exit(1)
}

func main() {
	// 统一 chdir 到 moonbit/（沿 gen_diag 先例）：moon fmt 须自 workspace 根
	// 调用；sourceRoot / outFile 均为 chdir 后的相对路径。
	if err := os.Chdir("moonbit"); err != nil {
		fmt.Fprintf(os.Stderr, "gen_stubs: 须在仓库根运行（找不到 moonbit/）: %v\n", err)
		os.Exit(2)
	}
	check := flag.Bool("check", false, "只校验产物未漂移，不写入")
	flag.Parse()

	names := loadHeaderNames()
	crossCheckDir(names)

	var digestInput bytes.Buffer
	var matchArms bytes.Buffer
	for _, name := range names {
		raw, err := os.ReadFile(filepath.Join(sourceRoot, name))
		if err != nil {
			fatalf("读取存根失败 %s: %v", name, err)
		}
		normalized := toLF(raw)
		digestInput.Write(normalized)
		// 已转义文本禁用 %q（会二次转义：`\n` 两字符被 %q 变成 "\\n"——
		// MoonBit 源里即字面反斜杠+n，曾致存根全部挤成一行 + 30 条 E1001）
		matchArms.WriteString(fmt.Sprintf("    \"%s\" => Some(\"%s\")\n", name, moonEscape(string(normalized))))
	}
	sum := sha256.Sum256(digestInput.Bytes())
	var out bytes.Buffer
	out.WriteString("// @generated by scripts/moonbit/gen_stubs —— 禁手改（git/diff 工具链按 @generated 识别；源 scripts/moonbit/libc_src/include/*.h（2026-10-05 迁出冻结区）；再生成：仓库根 go run ./scripts/moonbit/gen_stubs）\n")
	out.WriteString(fmt.Sprintf("// source sha256: %x（14 存根规范化行尾后按固定顺序拼接）\n", sum))
	out.WriteString("\n///|\n")
	out.WriteString("/// 标准库存根内容表（14 个；内容唯一来源 = Rust oracle 冻结资产，本文件为生成物）。\n")
	out.WriteString("pub fn stub_lookup(name : String) -> String? {\n")
	out.WriteString("  match name {\n")
	out.Write(matchArms.Bytes())
	out.WriteString("    _ => None\n")
	out.WriteString("  }\n")
	out.WriteString("}\n")

	// check 的还原基准（写前内容；文件不存在则记 nil）
	orig, origErr := os.ReadFile(outFile)

	// 产物形态以 moon fmt 为准：写入 gen 原始输出 → fmt → 以 fmt 后字节为准
	//（审阅 P3-8 探针实锤：磁盘=fmt 形态 vs gen 原始恒差 282B——「内容
	// 一致跳写」判据在 fmt 型生成器上结构性不可得；mtime 副作用由统一
	// 入口侧缓解——新鲜度警告是 stderr 提示非阻断；登记 #47 批五）
	if err := os.WriteFile(outFile, out.Bytes(), 0o644); err != nil {
		fatalf("写入失败: %v", err)
	}
	if fmtOut, err := exec.Command("moon", "fmt", outFile).CombinedOutput(); err != nil {
		if origErr == nil {
			_ = os.WriteFile(outFile, orig, 0o644)
		}
		fatalf("moon fmt 失败（moon 须在 PATH）: %v\n%s", err, fmtOut)
	}

	if !*check {
		fmt.Printf("gen_stubs: 已生成 %s（sha256 %x）\n", outFile, sum)
		return
	}
	// -check：fmt 后回读与写前内容比对（行尾归一——autocrlf checkout 的
	// CRLF 不得造成假红，与 gen_diag 同口径）。漂移即还原原内容再红，
	// check 不留副作用。
	now, err := os.ReadFile(outFile)
	if err != nil {
		fatalf("-check: 回读产物失败 %s: %v", outFile, err)
	}
	if origErr != nil || !bytes.Equal(toLF(now), toLF(orig)) {
		if origErr == nil {
			_ = os.WriteFile(outFile, orig, 0o644)
		}
		fatalf("-check: 产物漂移 %s——源已变更未再生成（go run ./scripts/moonbit/gen_stubs）", outFile)
	}
	fmt.Printf("gen_stubs: check OK（产物与源一致，未漂移；sha256 %x）\n", sum)
}
