package main

// emit_mbt.go：.json.mbt 真源 emit + round-trip 对拍（铺开批 2026-10-07）。
// codegen digest = 节×(sources StringMap + cases 条目对象Map)——cases 条目
// 三可选字段建模两态 enum（Ok{result_sha} / Fail{fail_stage}）。

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"vitro/scripts/jmemit"
)

const cgDigestMbt = "scripts/codegen_diff/golden_digest.json.mbt"

func emitCgMbt(d cgDigestDoc) {
	raw, err := os.ReadFile(cgDigestFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "emit: 读 %s: %v\n", cgDigestFile, err)
		os.Exit(1)
	}
	names := sortedKeys2(d.Corpora)
	secs := []cgSecEmit{}
	for _, name := range names {
		sec := d.Corpora[name]
		srcOrd := jmemit.KeyOrderOfScalars(raw, name)
		if len(srcOrd) != len(sec.Sources) {
			srcOrd = sortedKeys2(sec.Sources)
		}
		secs = append(secs, cgSecEmit{name, sec, srcOrd, sortedKeys3(sec.Cases)})
	}
	jmemit.EmitAndVerify(cgDigestMbt, raw, func(_ map[string][]string) string {
		return emitCgSections(d.Version, d.Note, secs)
	}, func(regen []byte) int {
		var rd struct {
			Sections map[string]struct {
				Sources map[string]string     `json:"sources"`
				Cases   map[string]cgEmitCase `json:"cases"`
			} `json:"sections"`
		}
		if err := json.Unmarshal(regen, &rd); err != nil {
			fmt.Fprintf(os.Stderr, "emit: 再生件解析失败: %v\n", err)
			return 1
		}
		bad := 0
		for name, sec := range d.Corpora {
			r, ok := rd.Sections[name]
			if !ok {
				fmt.Fprintf(os.Stderr, "emit: 丢节 %s\n", name)
				bad++
				continue
			}
			if !strMapsEqual(sec.Sources, r.Sources) || len(sec.Cases) != len(r.Cases) {
				fmt.Fprintf(os.Stderr, "emit: 漂移节 %s\n", name)
				bad++
				continue
			}
			for k, v := range sec.Cases {
				rv := r.Cases[k]
				if rv.ResultSha != v.ResultSHA || rv.Fail != v.Fail || rv.FailStage != v.FailStage {
					fmt.Fprintf(os.Stderr, "emit: 漂移条目 %s/%s\n", name, k)
					bad++
				}
			}
		}
		return bad
	})
}

type cgSecEmit struct {
	name      string
	sec       *cgSec
	srcOrder  []string
	caseOrder []string
}

type cgEmitCase struct {
	ResultSha string `json:"result_sha,omitempty"`
	Fail      bool   `json:"fail,omitempty"`
	FailStage string `json:"fail_stage,omitempty"`
}

func emitCgSections(version int, note string, secs []cgSecEmit) string {
	var b strings.Builder
	w := func(s string) { b.WriteString(s + "\n") }
	w("// @generated by codegen_diff freeze (scripts/jmemit) —— 禁手改（再生成：freeze 循环）。")
	w("pub struct OkCase {")
	w("  result_sha : String")
	w("}")
	w("")
	w("pub struct FailCase {")
	w("  fail : Bool")
	w("  fail_stage : String")
	w("}")
	w("")
	w("enum CaseE {")
	w("  Ok(OkCase)")
	w("  Fail(FailCase)")
	w("}")
	w("")
	w("pub struct Section {")
	w("  sources : Map[String, String]")
	w("  cases : Map[String, CaseE]")
	w("}")
	w("")
	w("pub struct Digest {")
	w("  version : Int")
	w("  note : String")
	w("  sections : Map[String, Section]")
	w("}")
	w("")
	w("pub let golden_digest : Digest = Digest::{")
	fmt.Fprintf(&b, "  version: %d,\n", version)
	fmt.Fprintf(&b, "  note: %s,\n", jmemit.Quote(note))
	w("  sections: {")
	for _, s := range secs {
		fmt.Fprintf(&b, "    %s: Section::{\n", jmemit.Quote(s.name))
		w("      sources: {")
		for _, n := range s.srcOrder {
			fmt.Fprintf(&b, "        %s: %s,\n", jmemit.Quote(n), jmemit.Quote(s.sec.Sources[n]))
		}
		w("      },")
		w("      cases: {")
		for _, n := range s.caseOrder {
			e := s.sec.Cases[n]
			if e.Fail {
				fmt.Fprintf(&b, "        %s: Fail(FailCase::{ fail: true, fail_stage: %s }),\n", jmemit.Quote(n), jmemit.Quote(e.FailStage))
			} else {
				fmt.Fprintf(&b, "        %s: Ok(OkCase::{ result_sha: %s }),\n", jmemit.Quote(n), jmemit.Quote(e.ResultSHA))
			}
		}
		w("      },")
		w("    },")
	}
	w("  },")
	w("}")
	return b.String()
}

func sortedKeys3[T any](m map[string]T) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	for i := 1; i < len(ks); i++ {
		for j := i; j > 0 && ks[j] < ks[j-1]; j-- {
			ks[j], ks[j-1] = ks[j-1], ks[j]
		}
	}
	return ks
}

func sortedKeys2[T any](m map[string]T) []string { return sortedKeys3(m) }

func strMapsEqual(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if b[k] != v {
			return false
		}
	}
	return true
}
