// gen_libc_data：Bytecode Libc 产物 → MoonBit 数据字面量生成器（批四号）。
//
// 源 = native/crates/vitro_vm/src/bytecode_libc_data.json（Rust include_str!
// 的同一份产物——单一真相源不变，本脚本是派生器）。
// 产物 = moonbit/vm/libc_data_gen.mbt（禁手改，文件头源 sha256 落款）。
//
// 数据形态（紧凑扁平，避免 563KB JSON 字符串字面量撑爆 moon fmt）：
//
//	LIBC_CODE_FLAT : Array[Int]     —— 每指令 5 元（opcode/operand/line/column/file_id）
//	LIBC_FUNC_ENTRIES : Array[LibcFuncEntry] —— 88 条（name + meta 字段 + 固定索引）
//	LIBC_GLOBALS_32 / 常量池等小字段直出
//
// 运行时由 vm/libc_setup.mbt 组装（不走 @json——wasm 后端无文件系统、
// 563KB 字符串字面量与 moon fmt 互踩）。
//
//	go run ./scripts/moonbit/gen_libc_data            # 生成
//	go run ./scripts/moonbit/gen_libc_data -check     # 幂等校验（CI）
package main

import (
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type instrJSON struct {
	Op      string `json:"op"`
	Operand int    `json:"operand"`
	Loc     struct {
		Line   int `json:"line"`
		Column int `json:"column"`
		FileID int `json:"file_id"`
	} `json:"loc"`
}

type funcMetaJSON struct {
	IP         int   `json:"ip"`
	ArgCount   int   `json:"arg_count"`
	ParamCount int   `json:"param_count"`
	LocalCount int   `json:"local_count"`
	ParamSizes []int `json:"param_sizes"`
	IsVariadic bool  `json:"is_variadic"`
	LocalBufs  []struct {
		Offset int    `json:"offset"`
		Size   int    `json:"size"`
		Name   string `json:"name"`
	} `json:"local_buffers"`
	ReturnType interface{} `json:"return_type"`
}

type artifactJSON struct {
	Code         []instrJSON             `json:"code"`
	CodeLen      int                     `json:"code_len"`
	FuncTable    map[string]funcMetaJSON `json:"func_table"`
	FuncIndex    map[string]int          `json:"func_index"`
	Globals32    [][2]int                `json:"globals_init_32"`
	Globals64    [][2]uint64             `json:"globals_init_64"`
	F64Constants []float64               `json:"f64_constants"`
	I64Constants []int64                 `json:"i64_constants"`
	StringData   [][2]interface{}        `json:"string_data"`
	Version      int                     `json:"version"`
}

func main() {
	check := flag.Bool("check", false, "幂等校验：源未变产物必须未漂移")
	flag.Parse()

	srcPath := filepath.Join("native", "crates", "vitro_vm", "src", "bytecode_libc_data.json")
	raw, err := os.ReadFile(srcPath)
	must(err, "读源 "+srcPath)
	srcSha := fmt.Sprintf("%x", sha256.Sum256(raw))

	var art artifactJSON
	must(json.Unmarshal(raw, &art), "解析 JSON")

	// 六轮审阅 P3-1：MoonBit 侧 LibcArtifact 无 string_data 字段（当前
	// 空数组无影响），静默丢弃 = 潜伏缺口且无闸可发现——非空即 fail loud，
	// 迫使人工评估装载面（oracle compile_pipeline.rs:367 写两处：libc +
	// 用户；MoonBit 侧仅用户段）。
	if len(art.StringData) > 0 {
		fmt.Fprintf(os.Stderr, "gen_libc_data: string_data 非空（%d 条）——MoonBit LibcArtifact 尚无该字段，先扩装载面再生成\n", len(art.StringData))
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("// @generated by scripts/moonbit/gen_libc_data —— 禁手改（git/diff 工具链按 @generated 识别；源 sha256 落款见下）。\n")
	b.WriteString("// 源：native/crates/vitro_vm/src/bytecode_libc_data.json（Rust include_str! 同一份）\n")
	fmt.Fprintf(&b, "// source_sha256=%s\n", srcSha)
	b.WriteString("// 生成命令：go run ./scripts/moonbit/gen_libc_data（流程内置 moon fmt）\n\n")

	// code 扁平数组
	b.WriteString("///| 扁平指令流（每指令 5 元：opcode/operand/line/column/file_id——\n///| 运行时 libc_setup.mbt 组装为 Instruction）。\n")
	b.WriteString("let libc_code_flat : Array[Int] = [\n")
	for i, in := range art.Code {
		if i%10 == 0 {
			fmt.Fprintf(&b, "  // %d\n", i)
		}
		fmt.Fprintf(&b, "  %d, %d, %d, %d, %d,\n",
			opCodeNumber(in.Op), in.Operand, in.Loc.Line, in.Loc.Column, in.Loc.FileID)
	}
	b.WriteString("]\n\n")

	// func entries（按固定索引排序——索引来自 func_index）
	b.WriteString("///| 函数表（name → meta；固定索引在 LIBC_FUNC_INDEX 中）。\n")
	b.WriteString("let libc_func_names : Array[String] = [\n")
	names := make([]string, 0, len(art.FuncIndex))
	for n := range art.FuncIndex {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool { return art.FuncIndex[names[i]] < art.FuncIndex[names[j]] })
	for _, n := range names {
		fmt.Fprintf(&b, "  %q,\n", n)
	}
	b.WriteString("]\n\n")
	b.WriteString("let libc_func_index : Array[Int] = [\n")
	for _, n := range names {
		fmt.Fprintf(&b, "  %d,\n", art.FuncIndex[n])
	}
	b.WriteString("]\n\n")

	// 每函数 meta 扁平：ip/arg/param/local/variadic + param_sizes
	b.WriteString("///| 每函数 meta 扁平（ip/arg_count/param_count/local_count/variadic + param_sizes 至 local_count 槽）。\n")
	b.WriteString("let libc_func_meta : Array[Int] = [\n")
	for _, n := range names {
		m := art.FuncTable[n]
		v := 0
		if m.IsVariadic {
			v = 1
		}
		fmt.Fprintf(&b, "  %d, %d, %d, %d, %d, %d, // %s\n",
			m.IP, m.ArgCount, m.ParamCount, m.LocalCount, v, len(m.ParamSizes), n)
		for _, ps := range m.ParamSizes {
			fmt.Fprintf(&b, "  %d,\n", ps)
		}
	}
	b.WriteString("]\n\n")

	// 小字段
	b.WriteString("let libc_globals_32 : Array[(UInt, Int)] = [\n")
	for _, g := range art.Globals32 {
		fmt.Fprintf(&b, "  (%dU, %d),\n", g[0], g[1])
	}
	b.WriteString("]\n\n")
	b.WriteString("let libc_globals_64 : Array[(UInt, UInt64)] = [\n")
	for _, g := range art.Globals64 {
		fmt.Fprintf(&b, "  (%dU, %dUL),\n", g[0], g[1])
	}
	b.WriteString("]\n\n")
	b.WriteString("let libc_f64_constants : Array[Double] = [\n")
	for _, c := range art.F64Constants {
		fmt.Fprintf(&b, "  %v,\n", c)
	}
	b.WriteString("]\n\n")
	b.WriteString("let libc_i64_constants : Array[Int64] = [\n")
	for _, c := range art.I64Constants {
		fmt.Fprintf(&b, "  %dL,\n", c)
	}
	b.WriteString("]\n\n")
	fmt.Fprintf(&b, "const LIBC_CODE_LEN : Int = %d\n", art.CodeLen)

	out := b.String()
	outPath := filepath.Join("moonbit", "vm", "libc_data_gen.mbt")
	if *check {
		// 同流程比对（gen_diag 模式）：重生成到临时文件 + 同样过 fmt，
		// 与现产物字节比——「生成路径」与「校验路径」完全一致。
		tmp := filepath.Join("moonbit", "vm", "libc_data_gen_check_tmp.mbt") // .mbt 结尾才会被 moon fmt 处理
		must(os.WriteFile(tmp, []byte(out), 0o644), "写临时产物")
		if err := runMoonFmt(); err != nil { // fmt 整包（含 tmp）
			fmt.Fprintf(os.Stderr, "gen_libc_data: moon fmt: %v\n", err)
			os.Exit(1)
		}
		cur, err := os.ReadFile(outPath)
		must(err, "读产物（先跑一次生成）")
		tmpB, err := os.ReadFile(tmp)
		must(err, "读临时产物")
		os.Remove(tmp)
		if norm(cur) != norm(tmpB) {
			fmt.Fprintln(os.Stderr, "gen_libc_data: 产物漂移（源变或产物被篡改）——重跑生成")
			os.Exit(1)
		}
		fmt.Println("gen_libc_data: check OK（产物与源一致）")
		return
	}
	must(os.WriteFile(outPath, []byte(out), 0o644), "写产物")
	// 生成流程内置 moon fmt（gen_diag 模式：fmt 重排产物形态——不内置则
	// 干净仓库上 -check 必红）
	if err := runMoonFmt(); err != nil {
		fmt.Fprintf(os.Stderr, "gen_libc_data: moon fmt: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("gen_libc_data: 写 %s（%d 指令 / %d 函数）\n", outPath, len(art.Code), len(names))
}

// runMoonFmt：对产物跑 moon fmt（cwd=moonbit）。
func runMoonFmt() error {
	cmd := exec.Command("moon", "fmt")
	cmd.Dir = "moonbit"
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%v: %s", err, string(out))
	}
	return nil
}

// opCodeNumber：op 名 → 编号（与 @opcode.OpCode::code 一致——**查询表由
// MoonBit 侧 from_name 提供**，此处内嵌最小映射避免双向漂移；生成期对不上
// 即 fail loud）。
var opNumbers = map[string]int{}

func opCodeNumber(name string) int {
	if v, ok := opNumbers[name]; ok {
		return v
	}
	// 首次调用时从 opcode 表惰性装载不可行（Go 无反射到 MoonBit）——
	// 直接从 opcode.mbt 抽取。六轮审阅 P3-4：只扫 `pub fn OpCode::code`
	// 的 match 体（此前无窗口约束扫全文件——opcode.mbt 新增任何
	// `Name => Int` 形态的臂都会静默污染本表）+ 重名臂 fail loud。
	if len(opNumbers) == 0 {
		data, err := os.ReadFile(filepath.Join("moonbit", "opcode", "opcode.mbt"))
		must(err, "读 opcode.mbt")
		lines := strings.Split(string(data), "\n")
		start := -1
		for i, l := range lines {
			if strings.Contains(l, "pub fn OpCode::code") {
				start = i
				break
			}
		}
		if start < 0 {
			fmt.Fprintln(os.Stderr, "gen_libc_data: opcode.mbt 中未找到 pub fn OpCode::code")
			os.Exit(1)
		}
		for i := start; i < len(lines); i++ {
			l := lines[i]
			if i > start && l == "}" { // 函数收尾（行首 }）
				break
			}
			line := strings.TrimSpace(l)
			var n int
			var nm string
			if _, err := fmt.Sscanf(line, "%s => %d", &nm, &n); err == nil {
				if prev, dup := opNumbers[nm]; dup {
					fmt.Fprintf(os.Stderr, "gen_libc_data: code() 体内重名臂 %s（%d 与 %d）\n", nm, prev, n)
					os.Exit(1)
				}
				opNumbers[nm] = n
			}
		}
		if len(opNumbers) < 100 {
			fmt.Fprintf(os.Stderr, "gen_libc_data: code() 体内仅抽到 %d 臂（<100，窗口判定可疑）\n", len(opNumbers))
			os.Exit(1)
		}
	}
	v, ok := opNumbers[name]
	if !ok {
		fmt.Fprintf(os.Stderr, "gen_libc_data: 未知 opcode %q（opcode.mbt 无此名）\n", name)
		os.Exit(1)
	}
	return v
}

func norm(b []byte) string {
	s := strings.ReplaceAll(string(b), "\r\n", "\n")
	return s
}

func must(err error, what string) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen_libc_data: %s: %v\n", what, err)
		os.Exit(1)
	}
}
