// @generated by scripts/gen_demo_algorithms — 勿手改（改生成器后重跑；-check 入 CI）
// 43 算法族 = teaching/steps 全集（rules.json 机判）；中文名 = golden display_name
// + detect_*.mbt build_match 提取；示例源码 = templates/ 代表（golden 首现）
// + extra/ 覆盖源；同族其余模板 = variants；未归类模板 = 扩展练习组
//（2026-10-04，refs #28 + 用户拍板全量纳入：82 个 .c 模板全覆盖——
// cpp_ 前缀不进，F-2 已裁砍 C++，class/template 编译必败）。
"use strict";

// 分组 × 族清单；source = 可直接载入编辑器的判据命中示例；
// variants = 同族其它模板（点击切换示例形态）；xlab = 扩展练习。
const DEMO_ALGORITHMS = {
  groups: [
    { id: "sorting", label: "排序", items: [
      { id: "bubble_sort", name: "冒泡排序", template: "bubble", source: `#include <stdio.h>

void bubbleSort(int arr[], int n) {
    for (int i = 0; i < n - 1; i++) {
        for (int j = 0; j < n - i - 1; j++) {
            if (arr[j] > arr[j + 1]) {
                int temp = arr[j];
                arr[j] = arr[j + 1];
                arr[j + 1] = temp;
            }
        }
    }
}

int main() {
    int arr[ 5] = {5, 3, 8, 1, 2};
    int n =  5;
    bubbleSort(arr, n);
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "insertion_sort", name: "插入排序", template: "insertion", source: `#include <stdio.h>

void insertionSort(int arr[], int n) {
    for (int i = 1; i < n; i++) {
        int key = arr[i];
        int j = i - 1;
        while (j >= 0 && arr[j] > key) {
            arr[j + 1] = arr[j];
            j--;
        }
        arr[j + 1] = key;
    }
}

int main() {
    int arr[ 5] = {12, 11, 13, 5, 6};
    int n =  5;
    insertionSort(arr, n);
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "merge_sort", name: "归并排序", template: "merge", source: `#include <stdio.h>

void merge(int arr[], int left, int mid, int right) {
    int n1 = mid - left + 1;
    int n2 = right - mid;
    int L[10], R[10];
    for (int i = 0; i < n1; i++) L[i] = arr[left + i];
    for (int j = 0; j < n2; j++) R[j] = arr[mid + 1 + j];
    int i = 0, j = 0, k = left;
    while (i < n1 && j < n2) {
        if (L[i] <= R[j]) arr[k++] = L[i++];
        else arr[k++] = R[j++];
    }
    while (i < n1) arr[k++] = L[i++];
    while (j < n2) arr[k++] = R[j++];
}

void mergeSort(int arr[], int left, int right) {
    if (left < right) {
        int mid = left + (right - left) / 2;
        mergeSort(arr, left, mid);
        mergeSort(arr, mid + 1, right);
        merge(arr, left, mid, right);
    }
}

int main() {
    int arr[ 5] = {12, 11, 13, 5, 6};
    int n =  5;
    mergeSort(arr, 0, n - 1);
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "quick_sort", name: "快速排序", template: "quick", source: `#include <stdio.h>

void quickSort(int arr[], int low, int high) {
    if (low < high) {
        int pivot = partition(arr, low, high);
        quickSort(arr, low, pivot - 1);
        quickSort(arr, pivot + 1, high);
    }
}

int partition(int arr[], int low, int high) {
    int pivot = arr[high];
    int i = low - 1;
    for (int j = low; j < high; j++) {
        if (arr[j] <= pivot) {
            i++;
            int temp = arr[i];
            arr[i] = arr[j];
            arr[j] = temp;
        }
    }
    int temp = arr[i + 1];
    arr[i + 1] = arr[high];
    arr[high] = temp;
    return i + 1;
}

int main() {
    int arr[ 5] = {10, 7, 8, 9, 1};
    int n =  5;
    quickSort(arr, 0, n - 1);
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "selection_sort", name: "选择排序", template: "selection", source: `#include <stdio.h>

void selectionSort(int arr[], int n) {
    for (int i = 0; i < n - 1; i++) {
        int minIdx = i;
        for (int j = i + 1; j < n; j++) {
            if (arr[j] < arr[minIdx])
                minIdx = j;
        }
        int temp = arr[i];
        arr[i] = arr[minIdx];
        arr[minIdx] = temp;
    }
}

int main() {
    int arr[ 5] = {64, 25, 12, 22, 11};
    int n =  5;
    selectionSort(arr, n);
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "heap_sort", name: "堆排序", template: "heapSort", source: `#include <stdio.h>

void heapify(int arr[], int n, int i) {
    int largest = i;
    int left = 2 * i + 1;
    int right = 2 * i + 2;
    if (left < n && arr[left] > arr[largest])
        largest = left;
    if (right < n && arr[right] > arr[largest])
        largest = right;
    if (largest != i) {
        int temp = arr[i];
        arr[i] = arr[largest];
        arr[largest] = temp;
        heapify(arr, n, largest);
    }
}

void heapSort(int arr[], int n) {
    for (int i = n / 2 - 1; i >= 0; i--)
        heapify(arr, n, i);
    for (int i = n - 1; i > 0; i--) {
        int temp = arr[0];
        arr[0] = arr[i];
        arr[i] = temp;
        heapify(arr, i, 0);
    }
}

int main() {
    int arr[ 5] = {12, 11, 13, 5, 6};
    int n =  5;
    heapSort(arr, n);
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "counting_sort", name: "计数排序", template: "countingSort", source: `#include <stdio.h>

void countingSort(int arr[], int n) {
    int count[10] = {0};
    for (int i = 0; i < n; i++) {
        count[arr[i]]++;
    }
    int index = 0;
    for (int i = 0; i < 10; i++) {
        while (count[i] > 0) {
            arr[index++] = i;
            count[i]--;
        }
    }
}

int main() {
    int arr[ 5] = {4, 2, 2, 8, 3};
    int n =  5;
    countingSort(arr, n);
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "shell_sort", name: "希尔排序", template: "shellSort", source: `#include <stdio.h>

void shellSort(int arr[], int n) {
    for (int gap = n / 2; gap > 0; gap /= 2) {
        for (int i = gap; i < n; i++) {
            int temp = arr[i];
            int j;
            for (j = i; j >= gap && arr[j - gap] > temp; j -= gap)
                arr[j] = arr[j - gap];
            arr[j] = temp;
        }
    }
}

int main() {
    int arr[ 5] = {64, 34, 25, 12, 22};
    int n =  5;
    shellSort(arr, n);
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "radix_sort", name: "基数排序", template: "radixSort", source: `#include <stdio.h>

void RadixSort(int arr[], int n) {
    int max = arr[0];
    for (int i = 1; i < n; i++) {
        if (arr[i] > max) max = arr[i];
    }
    int exp;
    int output[10];
    int count[10];
    for (exp = 1; max / exp > 0; exp *= 10) {
        for (int i = 0; i < 10; i++) count[i] = 0;
        for (int i = 0; i < n; i++) count[(arr[i] / exp) % 10]++;
        for (int i = 1; i < 10; i++) count[i] += count[i - 1];
        for (int i = n - 1; i >= 0; i--) {
            output[count[(arr[i] / exp) % 10] - 1] = arr[i];
            count[(arr[i] / exp) % 10]--;
        }
        for (int i = 0; i < n; i++) arr[i] = output[i];
    }
}

int main() {
    int arr[7] = {170, 45, 75, 90, 2, 802, 24};
    int n = 7;
    RadixSort(arr, n);
    for (int i = 0; i < n; i++) printf("%d ", arr[i]);
    printf("\\n");
    return 0;
}
`, variants: [] },
    ] },
    { id: "search", label: "查找", items: [
      { id: "binary_search", name: "二分查找", template: "binary", source: `#include <stdio.h>

int binarySearch(int arr[], int n, int target) {
    int left = 0, right = n - 1;
    while (left <= right) {
        int mid = left + (right - left) / 2;
        if (arr[mid] == target) return mid;
        if (arr[mid] < target) left = mid + 1;
        else right = mid - 1;
    }
    return -1;
}

int main() {
    int arr[] = {1, 3, 5, 7, 9};
    int n = 5;
    int target =  5;
    int result = binarySearch(arr, n, target);
    printf("%d\\n", result);
    return 0;
}
`, variants: [] },
      { id: "is_prime", name: "素数判断", template: "extra", source: `#include <stdio.h>

int isPrime(int n) {
    if (n <= 1) return 0;
    for (int i = 2; i * i <= n; i++) {
        if (n % i == 0) return 0;
    }
    return 1;
}

int main() {
    int count = 0;
    for (int n = 2; n <= 30; n++) {
        if (isPrime(n)) {
            printf("%d ", n);
            count++;
        }
    }
    printf("\\n共 %d 个素数\\n", count);
    return 0;
}
`, variants: [
        { tpl: "isPrime", source: `#include <stdio.h>

int isPrime(int n) {
    if (n <= 1) return 0;
    for (int i = 2; i * i <= n; i++) {
        if (n % i == 0) return 0;
    }
    return 1;
}

int main() {
    int n =  17;
    if (isPrime(n))
        printf("%d is prime\\n", n);
    else
        printf("%d is not prime\\n", n);
    return 0;
}
` }
      ] },
    ] },
    { id: "graph", label: "图", items: [
      { id: "bfs", name: "BFS 广度优先搜索", template: "bfs", source: `#include <stdio.h>

int graph[5][5] = {
    {0, 1, 1, 0, 0},
    {1, 0, 0, 1, 1},
    {1, 0, 0, 0, 0},
    {0, 1, 0, 0, 0},
    {0, 1, 0, 0, 0}
};
int visited[5] = {0, 0, 0, 0, 0};
int queue[5];
int front = 0, rear = 0;

void bfs(int start, int n) {
    visited[start] = 1;
    queue[rear++] = start;
    while (front < rear) {
        int u = queue[front++];
        printf("%d ", u);
        for (int v = 0; v < n; v++) {
            if (graph[u][v] == 1 && visited[v] == 0) {
                visited[v] = 1;
                queue[rear++] = v;
            }
        }
    }
}

int main() {
    int n =  5;
    bfs(0, n);
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "dfs", name: "DFS 深度优先搜索", template: "dfs", source: `#include <stdio.h>

int graph[5][5] = {
    {0, 1, 1, 0, 0},
    {1, 0, 0, 1, 1},
    {1, 0, 0, 0, 0},
    {0, 1, 0, 0, 0},
    {0, 1, 0, 0, 0}
};
int visited[5] = {0, 0, 0, 0, 0};

void dfs(int u, int n) {
    visited[u] = 1;
    printf("%d ", u);
    for (int v = 0; v < n; v++) {
        if (graph[u][v] == 1 && visited[v] == 0) {
            dfs(v, n);
        }
    }
}

int main() {
    int n =  5;
    dfs(0, n);
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "dijkstra", name: "Dijkstra 最短路径", template: "dijkstra", source: `#include <stdio.h>
#define MAXV 5
#define INF 65535

void Dijkstra(int G[][MAXV], int n, int v0) {
    int dist[MAXV];
    int visited[MAXV];
    for (int i = 0; i < n; i++) {
        dist[i] = G[v0][i];
        visited[i] = 0;
    }
    visited[v0] = 1;
    for (int i = 1; i < n; i++) {
        int min = INF;
        int u = -1;
        for (int j = 0; j < n; j++) {
            if (!visited[j] && dist[j] < min) {
                min = dist[j];
                u = j;
            }
        }
        if (u == -1) break;
        visited[u] = 1;
        for (int j = 0; j < n; j++) {
            if (!visited[j] && G[u][j] != INF && dist[u] + G[u][j] < dist[j]) {
                dist[j] = dist[u] + G[u][j];
            }
        }
    }
    for (int i = 0; i < n; i++) {
        printf("%d ", dist[i]);
    }
    printf("\\n");
}

int main() {
    int G[MAXV][MAXV] = {
        {0, 2, INF, 6, INF},
        {2, 0, 3, 8, 5},
        {INF, 3, 0, INF, 7},
        {6, 8, INF, 0, 9},
        {INF, 5, 7, 9, 0}
    };
    Dijkstra(G, MAXV, 0);
    return 0;
}
`, variants: [] },
      { id: "floyd", name: "Floyd 最短路径", template: "floyd", source: `#include <stdio.h>
#define MAXV 4
#define INF 65535

void Floyd(int G[][MAXV], int n) {
    for (int k = 0; k < n; k++) {
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                if (G[i][k] + G[k][j] < G[i][j]) {
                    G[i][j] = G[i][k] + G[k][j];
                }
            }
        }
    }
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            if (G[i][j] == INF) printf("INF ");
            else printf("%d ", G[i][j]);
        }
        printf("\\n");
    }
}

int main() {
    int G[MAXV][MAXV] = {
        {0, 2, 6, INF},
        {INF, 0, 3, INF},
        {INF, INF, 0, 1},
        {INF, INF, INF, 0}
    };
    Floyd(G, MAXV);
    return 0;
}
`, variants: [] },
      { id: "kruskal_mst", name: "Kruskal 最小生成树", template: "kruskalMST", source: `#include <stdio.h>
#define MAXE 10
#define MAXV 5

typedef struct {
    int u;
    int v;
    int w;
} Edge;

int Find(int parent[], int x) {
    if (parent[x] != x) parent[x] = Find(parent, parent[x]);
    return parent[x];
}

void Union(int parent[], int x, int y) {
    parent[Find(parent, x)] = Find(parent, y);
}

void Kruskal(Edge edges[], int n, int e) {
    int parent[MAXV];
    for (int i = 0; i < n; i++) parent[i] = i;
    for (int i = 0; i < e - 1; i++) {
        int min = i;
        for (int j = i + 1; j < e; j++) {
            if (edges[j].w < edges[min].w) min = j;
        }
        if (min != i) {
            Edge tmp = edges[i];
            edges[i] = edges[min];
            edges[min] = tmp;
        }
    }
    for (int i = 0; i < e; i++) {
        int u = edges[i].u;
        int v = edges[i].v;
        if (Find(parent, u) != Find(parent, v)) {
            printf("(%d,%d)=%d\\n", u, v, edges[i].w);
            Union(parent, u, v);
        }
    }
}

int main() {
    Edge edges[MAXE] = {
        {0, 1, 2}, {0, 3, 6}, {1, 2, 3},
        {1, 3, 8}, {1, 4, 5}, {2, 4, 7},
        {3, 4, 9}
    };
    Kruskal(edges, MAXV, 7);
    return 0;
}
`, variants: [] },
      { id: "prim_mst", name: "Prim 最小生成树", template: "primMST", source: `#include <stdio.h>
#define MAXV 5
#define INF 65535

void Prim(int G[][MAXV], int n) {
    int lowcost[MAXV];
    int adjvex[MAXV];
    lowcost[0] = 0;
    adjvex[0] = 0;
    for (int i = 1; i < n; i++) {
        lowcost[i] = G[0][i];
        adjvex[i] = 0;
    }
    for (int i = 1; i < n; i++) {
        int min = INF;
        int k = 0;
        for (int j = 1; j < n; j++) {
            if (lowcost[j] != 0 && lowcost[j] < min) {
                min = lowcost[j];
                k = j;
            }
        }
        printf("(%d,%d)=%d\\n", adjvex[k], k, min);
        lowcost[k] = 0;
        for (int j = 1; j < n; j++) {
            if (lowcost[j] != 0 && G[k][j] < lowcost[j]) {
                lowcost[j] = G[k][j];
                adjvex[j] = k;
            }
        }
    }
}

int main() {
    int G[MAXV][MAXV] = {
        {0, 2, INF, 6, INF},
        {2, 0, 3, 8, 5},
        {INF, 3, 0, INF, 7},
        {6, 8, INF, 0, 9},
        {INF, 5, 7, 9, 0}
    };
    Prim(G, MAXV);
    return 0;
}
`, variants: [] },
      { id: "topological_sort", name: "拓扑排序", template: "topologicalSort", source: `#include <stdio.h>
#define MAXV 6

void TopologicalSort(int G[][MAXV], int n) {
    int indegree[MAXV] = {0};
    int queue[MAXV];
    int front = 0, rear = 0;
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            if (G[i][j] != 0) indegree[j]++;
        }
    }
    for (int i = 0; i < n; i++) {
        if (indegree[i] == 0) queue[rear++] = i;
    }
    while (front < rear) {
        int u = queue[front++];
        printf("%d ", u);
        for (int v = 0; v < n; v++) {
            if (G[u][v] != 0) {
                indegree[v]--;
                if (indegree[v] == 0) queue[rear++] = v;
            }
        }
    }
    printf("\\n");
}

int main() {
    int G[MAXV][MAXV] = {
        {0, 1, 1, 0, 0, 0},
        {0, 0, 0, 1, 1, 0},
        {0, 0, 0, 1, 0, 0},
        {0, 0, 0, 0, 0, 1},
        {0, 0, 0, 0, 0, 1},
        {0, 0, 0, 0, 0, 0}
    };
    TopologicalSort(G, MAXV);
    return 0;
}
`, variants: [] },
    ] },
    { id: "tree", label: "树", items: [
      { id: "bst_insert", name: "BST 插入", template: "bstDelete", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

struct TreeNode* insert(struct TreeNode* root, int val) {
    if (root == NULL) return createNode(val);
    if (val < root->val)
        root->left = insert(root->left, val);
    else
        root->right = insert(root->right, val);
    return root;
}

struct TreeNode* findMin(struct TreeNode* root) {
    while (root->left != NULL) root = root->left;
    return root;
}

struct TreeNode* deleteNode(struct TreeNode* root, int key) {
    if (root == NULL) return NULL;
    if (key < root->val)
        root->left = deleteNode(root->left, key);
    else if (key > root->val)
        root->right = deleteNode(root->right, key);
    else {
        if (root->left == NULL) {
            struct TreeNode* temp = root->right;
            free(root);
            return temp;
        } else if (root->right == NULL) {
            struct TreeNode* temp = root->left;
            free(root);
            return temp;
        }
        struct TreeNode* temp = findMin(root->right);
        root->val = temp->val;
        root->right = deleteNode(root->right, temp->val);
    }
    return root;
}

void inorder(struct TreeNode* root) {
    if (root == NULL) return;
    inorder(root->left);
    printf("%d ", root->val);
    inorder(root->right);
}

int main() {
    struct TreeNode* root = NULL;
    root = insert(root, 5);
    insert(root, 3);
    insert(root, 7);
    insert(root, 2);
    insert(root, 4);
    insert(root, 6);
    insert(root, 8);
    root = deleteNode(root, 3);
    inorder(root);
    printf("\\n");
    return 0;
}
`, variants: [
        { tpl: "bstInsert", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

struct TreeNode* insert(struct TreeNode* root, int val) {
    if (root == NULL) return createNode(val);
    if (val < root->val)
        root->left = insert(root->left, val);
    else
        root->right = insert(root->right, val);
    return root;
}

void inorder(struct TreeNode* root) {
    if (root == NULL) return;
    inorder(root->left);
    printf("%d ", root->val);
    inorder(root->right);
}

int main() {
    struct TreeNode* root = NULL;
    root = insert(root, 5);
    insert(root, 3);
    insert(root, 7);
    insert(root, 1);
    insert(root, 9);
    inorder(root);
    printf("\\n");
    return 0;
}
` }, 
        { tpl: "bstSearch", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

struct TreeNode* insert(struct TreeNode* root, int val) {
    if (root == NULL) return createNode(val);
    if (val < root->val)
        root->left = insert(root->left, val);
    else
        root->right = insert(root->right, val);
    return root;
}

struct TreeNode* search(struct TreeNode* root, int key) {
    if (root == NULL || root->val == key) return root;
    if (key < root->val)
        return search(root->left, key);
    else
        return search(root->right, key);
}

int main() {
    struct TreeNode* root = NULL;
    root = insert(root, 5);
    insert(root, 3);
    insert(root, 7);
    insert(root, 1);
    insert(root, 9);
    struct TreeNode* res = search(root, 7);
    if (res != NULL)
        printf("Found %d\\n", res->val);
    else
        printf("Not found\\n");
    return 0;
}
` }
      ] },
      { id: "bst_search", name: "BST 查找", template: "bstSearch", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

struct TreeNode* insert(struct TreeNode* root, int val) {
    if (root == NULL) return createNode(val);
    if (val < root->val)
        root->left = insert(root->left, val);
    else
        root->right = insert(root->right, val);
    return root;
}

struct TreeNode* search(struct TreeNode* root, int key) {
    if (root == NULL || root->val == key) return root;
    if (key < root->val)
        return search(root->left, key);
    else
        return search(root->right, key);
}

int main() {
    struct TreeNode* root = NULL;
    root = insert(root, 5);
    insert(root, 3);
    insert(root, 7);
    insert(root, 1);
    insert(root, 9);
    struct TreeNode* res = search(root, 7);
    if (res != NULL)
        printf("Found %d\\n", res->val);
    else
        printf("Not found\\n");
    return 0;
}
`, variants: [] },
      { id: "bst_delete", name: "BST 删除", template: "bstDelete", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

struct TreeNode* insert(struct TreeNode* root, int val) {
    if (root == NULL) return createNode(val);
    if (val < root->val)
        root->left = insert(root->left, val);
    else
        root->right = insert(root->right, val);
    return root;
}

struct TreeNode* findMin(struct TreeNode* root) {
    while (root->left != NULL) root = root->left;
    return root;
}

struct TreeNode* deleteNode(struct TreeNode* root, int key) {
    if (root == NULL) return NULL;
    if (key < root->val)
        root->left = deleteNode(root->left, key);
    else if (key > root->val)
        root->right = deleteNode(root->right, key);
    else {
        if (root->left == NULL) {
            struct TreeNode* temp = root->right;
            free(root);
            return temp;
        } else if (root->right == NULL) {
            struct TreeNode* temp = root->left;
            free(root);
            return temp;
        }
        struct TreeNode* temp = findMin(root->right);
        root->val = temp->val;
        root->right = deleteNode(root->right, temp->val);
    }
    return root;
}

void inorder(struct TreeNode* root) {
    if (root == NULL) return;
    inorder(root->left);
    printf("%d ", root->val);
    inorder(root->right);
}

int main() {
    struct TreeNode* root = NULL;
    root = insert(root, 5);
    insert(root, 3);
    insert(root, 7);
    insert(root, 2);
    insert(root, 4);
    insert(root, 6);
    insert(root, 8);
    root = deleteNode(root, 3);
    inorder(root);
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "bst_validate", name: "BST 合法性校验", template: "binarySearchTreeValidation", source: `#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

int isValidBST(struct TreeNode* root, long long min, long long max) {
    if (root == NULL) return 1;
    if (root->val <= min || root->val >= max) return 0;
    return isValidBST(root->left, min, root->val) &&
           isValidBST(root->right, root->val, max);
}

int main() {
    struct TreeNode* root = createNode(5);
    root->left = createNode(3);
    root->right = createNode(7);
    root->left->left = createNode(1);
    root->left->right = createNode(4);
    if (isValidBST(root, (long long)INT_MIN - 1, (long long)INT_MAX + 1))
        printf("valid\\n");
    else
        printf("invalid\\n");
    return 0;
}
`, variants: [] },
      { id: "avl_tree", name: "AVL 树", template: "avlTree", source: `#include <stdio.h>
#include <stdlib.h>

struct AVLNode {
    int data;
    struct AVLNode* lchild;
    struct AVLNode* rchild;
    int bf;
};

struct AVLNode* createNode(int data) {
    struct AVLNode* node = (struct AVLNode*)malloc(sizeof(struct AVLNode));
    node->data = data;
    node->lchild = NULL;
    node->rchild = NULL;
    node->bf = 0;
    return node;
}

void R_Rotate(struct AVLNode** p) {
    struct AVLNode* lc = (*p)->lchild;
    (*p)->lchild = lc->rchild;
    lc->rchild = *p;
    *p = lc;
}

void L_Rotate(struct AVLNode** p) {
    struct AVLNode* rc = (*p)->rchild;
    (*p)->rchild = rc->lchild;
    rc->lchild = *p;
    *p = rc;
}

void LeftBalance(struct AVLNode** T) {
    struct AVLNode* lc = (*T)->lchild;
    switch (lc->bf) {
        case 1:
            (*T)->bf = lc->bf = 0;
            R_Rotate(T);
            break;
        case -1: {
            struct AVLNode* rd = lc->rchild;
            switch (rd->bf) {
                case 1: (*T)->bf = -1; lc->bf = 0; break;
                case 0: (*T)->bf = lc->bf = 0; break;
                case -1: (*T)->bf = 0; lc->bf = 1; break;
            }
            rd->bf = 0;
            L_Rotate(&((*T)->lchild));
            R_Rotate(T);
            break;
        }
    }
}

void RightBalance(struct AVLNode** T) {
    struct AVLNode* rc = (*T)->rchild;
    switch (rc->bf) {
        case -1:
            (*T)->bf = rc->bf = 0;
            L_Rotate(T);
            break;
        case 1: {
            struct AVLNode* ld = rc->lchild;
            switch (ld->bf) {
                case 1: (*T)->bf = 0; rc->bf = -1; break;
                case 0: (*T)->bf = rc->bf = 0; break;
                case -1: (*T)->bf = 1; rc->bf = 0; break;
            }
            ld->bf = 0;
            R_Rotate(&((*T)->rchild));
            L_Rotate(T);
            break;
        }
    }
}

int InsertAVL(struct AVLNode** T, int e) {
    if (*T == NULL) {
        *T = createNode(e);
        return 1;
    }
    if (e == (*T)->data) return 0;
    else if (e < (*T)->data) {
        if (!InsertAVL(&((*T)->lchild), e)) return 0;
        switch ((*T)->bf) {
            case 1: LeftBalance(T); break;
            case 0: (*T)->bf = 1; break;
            case -1: (*T)->bf = 0; break;
        }
    } else {
        if (!InsertAVL(&((*T)->rchild), e)) return 0;
        switch ((*T)->bf) {
            case -1: RightBalance(T); break;
            case 0: (*T)->bf = -1; break;
            case 1: (*T)->bf = 0; break;
        }
    }
    return 1;
}

void inorder(struct AVLNode* T) {
    if (T) {
        inorder(T->lchild);
        printf("%d ", T->data);
        inorder(T->rchild);
    }
}

int main() {
    struct AVLNode* T = NULL;
    InsertAVL(&T, 3);
    InsertAVL(&T, 2);
    InsertAVL(&T, 1);
    InsertAVL(&T, 4);
    InsertAVL(&T, 5);
    inorder(T);
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "huffman_tree", name: "哈夫曼树", template: "huffmanTree", source: `#include <stdio.h>
#define N 5
#define M 9

typedef struct {
    int weight;
    int parent;
    int lchild;
    int rchild;
} HTNode;

void Select(HTNode HT[], int n, int* s1, int* s2) {
    int min1 = 100000, min2 = 100000;
    *s1 = *s2 = -1;
    for (int i = 0; i < n; i++) {
        if (HT[i].parent == -1 && HT[i].weight < min1) {
            min2 = min1;
            *s2 = *s1;
            min1 = HT[i].weight;
            *s1 = i;
        } else if (HT[i].parent == -1 && HT[i].weight < min2) {
            min2 = HT[i].weight;
            *s2 = i;
        }
    }
}

void CreateHuffmanTree(HTNode HT[], int w[], int n) {
    int m = 2 * n - 1;
    for (int i = 0; i < m; i++) {
        HT[i].lchild = HT[i].rchild = HT[i].parent = -1;
    }
    for (int i = 0; i < n; i++) HT[i].weight = w[i];
    for (int i = n; i < m; i++) {
        int s1, s2;
        Select(HT, i, &s1, &s2);
        HT[s1].parent = i;
        HT[s2].parent = i;
        HT[i].lchild = s1;
        HT[i].rchild = s2;
        HT[i].weight = HT[s1].weight + HT[s2].weight;
    }
}

int main() {
    int w[N] = {5, 29, 7, 8, 14};
    HTNode ht[M];
    CreateHuffmanTree(ht, w, N);
    printf("root weight=%d\\n", ht[M-1].weight);
    return 0;
}
`, variants: [] },
      { id: "level_order", name: "层序遍历", template: "levelOrder", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

#define MAX 20

void levelOrder(struct TreeNode* root) {
    if (root == NULL) return;
    struct TreeNode* queue[MAX];
    int front = 0, rear = 0;
    queue[rear++] = root;
    while (front < rear) {
        struct TreeNode* node = queue[front++];
        printf("%d ", node->val);
        if (node->left != NULL) queue[rear++] = node->left;
        if (node->right != NULL) queue[rear++] = node->right;
    }
}

int main() {
    struct TreeNode* root = createNode(1);
    root->left = createNode(2);
    root->right = createNode(3);
    root->left->left = createNode(4);
    root->left->right = createNode(5);
    levelOrder(root);
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "threaded_binary_tree", name: "线索二叉树", template: "extra", source: `#include <stdio.h>
#include <stdlib.h>

#define LINK 0
#define THREAD 1

struct ThreadedNode {
    int data;
    struct ThreadedNode* left;
    struct ThreadedNode* right;
    int ltag;
    int rtag;
};

struct ThreadedNode* createThreadedNode(int data) {
    struct ThreadedNode* n = (struct ThreadedNode*)malloc(sizeof(struct ThreadedNode));
    n->data = data;
    n->left = NULL;
    n->right = NULL;
    n->ltag = LINK;
    n->rtag = LINK;
    return n;
}

void inorderThreadedTree(struct ThreadedNode* p, struct ThreadedNode** prev) {
    if (p == NULL) return;
    inorderThreadedTree(p->left, prev);
    if (p->left == NULL) {
        p->ltag = THREAD;
        p->left = *prev;
    }
    if (*prev != NULL && (*prev)->right == NULL) {
        (*prev)->rtag = THREAD;
        (*prev)->right = p;
    }
    *prev = p;
    inorderThreadedTree(p->right, prev);
}

int main() {
    struct ThreadedNode* a = createThreadedNode(1);
    struct ThreadedNode* b = createThreadedNode(2);
    struct ThreadedNode* c = createThreadedNode(3);
    a->left = b;
    a->right = c;
    struct ThreadedNode* prev = NULL;
    inorderThreadedTree(a, &prev);
    printf("线索化完成 ltag(b)=%d\\n", b->ltag);
    return 0;
}
`, variants: [
        { tpl: "threadedBinaryTree", source: `#include <stdio.h>
#include <stdlib.h>

typedef enum { Link, Thread } PointerTag;

struct BiThrNode {
    int data;
    struct BiThrNode* lchild;
    struct BiThrNode* rchild;
    PointerTag LTag;
    PointerTag RTag;
};

struct BiThrNode* createNode(int data) {
    struct BiThrNode* node = (struct BiThrNode*)malloc(sizeof(struct BiThrNode));
    node->data = data;
    node->lchild = NULL;
    node->rchild = NULL;
    node->LTag = Link;
    node->RTag = Link;
    return node;
}

struct BiThrNode* pre = NULL;

void InThreading(struct BiThrNode* p) {
    if (p) {
        InThreading(p->lchild);
        if (p->lchild == NULL) {
            p->LTag = Thread;
            p->lchild = pre;
        }
        if (pre && pre->rchild == NULL) {
            pre->RTag = Thread;
            pre->rchild = p;
        }
        pre = p;
        InThreading(p->rchild);
    }
}

void InOrderTraverse_Thr(struct BiThrNode* head) {
    struct BiThrNode* p = head->lchild;
    while (p != head) {
        while (p->LTag == Link) p = p->lchild;
        printf("%d ", p->data);
        while (p->RTag == Thread && p->rchild != head) {
            p = p->rchild;
            printf("%d ", p->data);
        }
        p = p->rchild;
    }
}

int main() {
    struct BiThrNode* head = createNode(0);
    head->LTag = Link;
    head->RTag = Thread;
    head->rchild = head;

    struct BiThrNode* root = createNode(1);
    root->lchild = createNode(2);
    root->rchild = createNode(3);
    root->lchild->lchild = createNode(4);
    root->lchild->rchild = createNode(5);

    head->lchild = root;
    InThreading(root);

    // 收尾：把中序第一个节点的左线索和最后一个节点的右线索都连回头节点。
    struct BiThrNode* first = root;
    while (first->LTag == Link) first = first->lchild;
    first->lchild = head;
    first->LTag = Thread;

    pre->rchild = head;
    pre->RTag = Thread;

    InOrderTraverse_Thr(head);
    printf("\\n");
    return 0;
}
` }
      ] },
    ] },
    { id: "structures", label: "结构", items: [
      { id: "linked_list_append", name: "链表尾插", template: "extra", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* appendNode(struct Node* head, int data) {
    struct Node* n = (struct Node*)malloc(sizeof(struct Node));
    n->data = data;
    n->next = NULL;
    if (head == NULL) return n;
    struct Node* p = head;
    while (p->next != NULL) p = p->next;
    p->next = n;
    return head;
}

int main() {
    struct Node* h = NULL;
    h = appendNode(h, 1);
    h = appendNode(h, 2);
    h = appendNode(h, 3);
    printf("%d %d %d\\n", h->data, h->next->data, h->next->next->data);
    return 0;
}
`, variants: [] },
      { id: "linked_list_delete", name: "链表删除", template: "extra", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* deleteNodeList(struct Node* head, int key) {
    struct Node* t = head;
    struct Node* prev = NULL;
    while (t != NULL && t->data != key) {
        prev = t;
        t = t->next;
    }
    if (t == NULL) return head;
    if (prev == NULL) head = t->next;
    else prev->next = t->next;
    free(t);
    return head;
}

int main() {
    struct Node* a = (struct Node*)malloc(sizeof(struct Node));
    struct Node* b = (struct Node*)malloc(sizeof(struct Node));
    struct Node* c = (struct Node*)malloc(sizeof(struct Node));
    a->data = 1;
    b->data = 2;
    c->data = 3;
    a->next = b;
    b->next = c;
    c->next = NULL;
    a = deleteNodeList(a, 2);
    printf("%d\\n", a->next->data);
    return 0;
}
`, variants: [] },
      { id: "static_linked_list", name: "静态链表", template: "extra", source: `#include <stdio.h>

#define MAX 8

// 静态链表（游标形态：space[i].cur 指向后继，0 号为备用链表头）
struct StaticNode {
    int data;
    int cur;
};

void staticListInit(struct StaticNode space[]) {
    for (int i = 0; i < MAX - 1; i++) {
        space[i].cur = i + 1;
    }
    space[MAX - 1].cur = 0;
    space[0].data = -1;
}

int staticListMalloc(struct StaticNode space[]) {
    int i = space[0].cur;
    if (space[0].cur) {
        space[0].cur = space[i].cur;
    }
    return i;
}

void staticListFree(struct StaticNode space[], int k) {
    space[k].cur = space[0].cur;
    space[0].cur = k;
}

int main() {
    struct StaticNode space[MAX];
    staticListInit(space);
    int a = staticListMalloc(space);
    int b = staticListMalloc(space);
    space[a].data = 11;
    space[b].data = 22;
    space[a].cur = b;
    space[b].cur = 0;
    printf("首节点 %d -> 次节点 %d\\n", space[a].data, space[b].data);
    staticListFree(space, b);
    return 0;
}
`, variants: [
        { tpl: "staticLinkedList", source: `#include <stdio.h>
#define MAXSIZE 10

struct Component {
    int data;
    int cur;
};

void initSpace(struct Component space[]) {
    for (int i = 0; i < MAXSIZE - 1; i++)
        space[i].cur = i + 1;
    space[MAXSIZE - 1].cur = 0;
}

int mallocNode(struct Component space[]) {
    int i = space[0].cur;
    if (i) space[0].cur = space[i].cur;
    return i;
}

void freeNode(struct Component space[], int k) {
    space[k].cur = space[0].cur;
    space[0].cur = k;
}

int main() {
    struct Component space[MAXSIZE];
    initSpace(space);
    int head = mallocNode(space);
    space[head].data = 10;
    int p = mallocNode(space);
    space[p].data = 20;
    space[head].cur = p;
    space[p].cur = 0;
    printf("%d %d\\n", space[head].data, space[space[head].cur].data);
    return 0;
}
` }
      ] },
      { id: "circular_linked_list", name: "循环链表", template: "extra", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* insertCircularList(struct Node* tail, int data) {
    struct Node* n = (struct Node*)malloc(sizeof(struct Node));
    n->data = data;
    if (tail == NULL) {
        n->next = n;
        return n;
    }
    n->next = tail->next;
    tail->next = n;
    return n;
}

void printCircularList(struct Node* tail) {
    if (tail == NULL) return;
    struct Node* p = tail->next;
    do {
        printf("%d ", p->data);
        p = p->next;
    } while (p != tail->next);
    printf("\\n");
}

int main() {
    struct Node* tail = NULL;
    tail = insertCircularList(tail, 1);
    tail = insertCircularList(tail, 2);
    tail = insertCircularList(tail, 3);
    printCircularList(tail);
    return 0;
}
`, variants: [
        { tpl: "circularLinkedList", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* createNode(int data) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node));
    node->data = data;
    node->next = NULL;
    return node;
}

struct Node* append(struct Node* head, int data) {
    struct Node* newNode = createNode(data);
    if (head == NULL) {
        newNode->next = newNode;
        return newNode;
    }
    struct Node* p = head;
    while (p->next != head) p = p->next;
    p->next = newNode;
    newNode->next = head;
    return head;
}

void printList(struct Node* head) {
    if (head == NULL) return;
    struct Node* p = head;
    do {
        printf("%d ", p->data);
        p = p->next;
    } while (p != head);
    printf("\\n");
}

int main() {
    struct Node* head = NULL;
    head = append(head, 1);
    append(head, 2);
    append(head, 3);
    printList(head);
    return 0;
}
` }
      ] },
      { id: "linked_stack", name: "链栈", template: "extra", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

int linkedStackEmpty(struct Node* top) {
    return top == NULL;
}

struct Node* linkedStackPush(struct Node* top, int x) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node)); node->next = top;
    node->data = x;
    return node;
}

struct Node* linkedStackPop(struct Node* top, int* out) {
    if (linkedStackEmpty(top)) return top;
    struct Node* temp = top;
    *out = temp->data;
    top = temp->next;
    free(temp);
    return top;
}

int main() {
    struct Node* top = NULL;
    int v = 0;
    top = linkedStackPush(top, 10);
    top = linkedStackPush(top, 20);
    top = linkedStackPush(top, 30);
    top = linkedStackPop(top, &v);
    printf("弹出 %d\\n", v);
    return 0;
}
`, variants: [
        { tpl: "linkedStack", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* push(struct Node* top, int x) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node));
    node->data = x;
    node->next = top;
    return node;
}

struct Node* pop(struct Node* top) {
    if (top == NULL) return NULL;
    struct Node* temp = top;
    top = top->next;
    free(temp);
    return top;
}

void printStack(struct Node* top) {
    struct Node* p = top;
    while (p != NULL) {
        printf("%d ", p->data);
        p = p->next;
    }
    printf("\\n");
}

int main() {
    struct Node* top = NULL;
    top = push(top, 30);
    top = push(top, 20);
    top = push(top, 10);
    printStack(top);
    top = pop(top);
    printStack(top);
    return 0;
}
` }
      ] },
      { id: "linked_queue", name: "链队列", template: "extra", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

int linkedQueueEmpty(struct Node* front, struct Node* rear) {
    return front == NULL && rear == NULL;
}

void linkedQueuePush(struct Node** front, struct Node** rear, int x) {
    struct Node* n = (struct Node*)malloc(sizeof(struct Node));
    n->data = x;
    n->next = NULL;
    if (*rear == NULL) {
        *front = n;
        *rear = n;
        return;
    }
    (*rear)->next = n;
    *rear = n;
}

int linkedQueuePop(struct Node** front, struct Node** rear) {
    if (linkedQueueEmpty(*front, *rear)) return -1;
    struct Node* t = *front;
    int v = t->data;
    *front = t->next;
    if (*front == NULL) *rear = NULL;
    free(t);
    return v;
}

int main() {
    struct Node* front = NULL;
    struct Node* rear = NULL;
    linkedQueuePush(&front, &rear, 1);
    linkedQueuePush(&front, &rear, 2);
    linkedQueuePush(&front, &rear, 3);
    printf("%d %d\\n", linkedQueuePop(&front, &rear), linkedQueuePop(&front, &rear));
    return 0;
}
`, variants: [
        { tpl: "linkedQueue", source: `#include <stdio.h>
#include <stdlib.h>

struct QNode {
    int data;
    struct QNode* next;
};

struct LinkedQueue {
    struct QNode* front;
    struct QNode* rear;
};

void init(struct LinkedQueue* q) {
    q->front = NULL;
    q->rear = NULL;
}

void enqueue(struct LinkedQueue* q, int x) {
    struct QNode* node = (struct QNode*)malloc(sizeof(struct QNode));
    node->data = x;
    node->next = NULL;
    if (q->rear == NULL) {
        q->front = node;
        q->rear = node;
    } else {
        q->rear->next = node;
        q->rear = node;
    }
}

int dequeue(struct LinkedQueue* q) {
    if (q->front == NULL) return -1;
    struct QNode* temp = q->front;
    int x = temp->data;
    q->front = q->front->next;
    if (q->front == NULL) q->rear = NULL;
    free(temp);
    return x;
}

int main() {
    struct LinkedQueue q;
    init(&q);
    enqueue(&q, 10);
    enqueue(&q, 20);
    enqueue(&q, 30);
    printf("%d ", dequeue(&q));
    printf("%d ", dequeue(&q));
    printf("%d\\n", dequeue(&q));
    return 0;
}
` }
      ] },
      { id: "circular_queue", name: "循环队列", template: "extra", source: `#include <stdio.h>

#define SIZE 5

struct CircularQueue {
    int data[SIZE];
    int front;
    int rear;
};

int circularQueueEmpty(struct CircularQueue* q) {
    return q->front == q->rear;
}

int circularQueuePush(struct CircularQueue* q, int x) {
    if ((q->rear + 1) % SIZE == q->front) return 0;
    q->data[q->rear] = x;
    q->rear = (q->rear + 1) % SIZE;
    return 1;
}

int circularQueuePop(struct CircularQueue* q) {
    if (circularQueueEmpty(q)) return -1;
    int v = q->data[q->front];
    q->front = (q->front + 1) % SIZE;
    return v;
}

int main() {
    struct CircularQueue q = { {0}, 0, 0 };
    circularQueuePush(&q, 10);
    circularQueuePush(&q, 20);
    circularQueuePush(&q, 30);
    printf("%d %d\\n", circularQueuePop(&q), circularQueuePop(&q));
    return 0;
}
`, variants: [
        { tpl: "circularQueue", source: `#include <stdio.h>
#define MAXSIZE 5

struct CircularQueue {
    int data[MAXSIZE];
    int front;
    int rear;
};

void init(struct CircularQueue* q) {
    q->front = 0;
    q->rear = 0;
}

int isEmpty(struct CircularQueue* q) {
    return q->front == q->rear;
}

int isFull(struct CircularQueue* q) {
    return (q->rear + 1) % MAXSIZE == q->front;
}

void enqueue(struct CircularQueue* q, int x) {
    if (isFull(q)) return;
    q->data[q->rear] = x;
    q->rear = (q->rear + 1) % MAXSIZE;
}

int dequeue(struct CircularQueue* q) {
    if (isEmpty(q)) return -1;
    int x = q->data[q->front];
    q->front = (q->front + 1) % MAXSIZE;
    return x;
}

int main() {
    struct CircularQueue q;
    init(&q);
    enqueue(&q, 10);
    enqueue(&q, 20);
    enqueue(&q, 30);
    printf("%d ", dequeue(&q));
    printf("%d ", dequeue(&q));
    printf("%d\\n", dequeue(&q));
    return 0;
}
` }
      ] },
      { id: "hash_table", name: "哈希表", template: "hashTable", source: `#include <stdio.h>
#define TABLE_SIZE 10

struct HashEntry {
    int key;
    int occupied;
};

int hash(int key) {
    return key % TABLE_SIZE;
}

void insert(struct HashEntry table[], int key) {
    int idx = hash(key);
    while (table[idx].occupied) {
        idx = (idx + 1) % TABLE_SIZE;
    }
    table[idx].key = key;
    table[idx].occupied = 1;
}

int search(struct HashEntry table[], int key) {
    int idx = hash(key);
    while (table[idx].occupied) {
        if (table[idx].key == key) return idx;
        idx = (idx + 1) % TABLE_SIZE;
    }
    return -1;
}

int main() {
    struct HashEntry table[TABLE_SIZE];
    for (int i = 0; i < TABLE_SIZE; i++) {
        table[i].occupied = 0;
    }
    insert(table, 5);
    insert(table, 15);
    insert(table, 25);
    int idx = search(table, 15);
    printf("%d\\n", idx);
    return 0;
}
`, variants: [] },
      { id: "seq_list", name: "顺序表", template: "seqList", source: `#include <stdio.h>
#define MAXSIZE 10

struct SeqList {
    int data[MAXSIZE];
    int length;
};

void init(struct SeqList* L) {
    L->length = 0;
}

int listInsert(struct SeqList* L, int pos, int x) {
    if (pos < 0 || pos > L->length || L->length >= MAXSIZE) return 0;
    for (int i = L->length; i > pos; i--)
        L->data[i] = L->data[i - 1];
    L->data[pos] = x;
    L->length++;
    return 1;
}

int listDelete(struct SeqList* L, int pos) {
    if (pos < 0 || pos >= L->length) return 0;
    for (int i = pos; i < L->length - 1; i++)
        L->data[i] = L->data[i + 1];
    L->length--;
    return 1;
}

int listFind(struct SeqList* L, int x) {
    for (int i = 0; i < L->length; i++) {
        if (L->data[i] == x) return i;
    }
    return -1;
}

int main() {
    struct SeqList L;
    init(&L);
    listInsert(&L, 0, 5);
    listInsert(&L, 1, 3);
    listInsert(&L, 2, 8);
    listDelete(&L, 1);
    for (int i = 0; i < L.length; i++) {
        printf("%d ", L.data[i]);
    }
    printf("\\n");
    return 0;
}
`, variants: [] },
      { id: "union_find", name: "并查集", template: "extra", source: `#include <stdio.h>

#define MAX 10

int unionFindParent[MAX];

void unionFindInit(int n) {
    for (int i = 0; i < n; i++) unionFindParent[i] = i;
}

int unionFindRoot(int x) {
    while (unionFindParent[x] != x) {
        unionFindParent[x] = unionFindParent[unionFindParent[x]];
        x = unionFindParent[x];
    }
    return x;
}

void unionFindMerge(int a, int b) {
    int ra = unionFindRoot(a);
    int rb = unionFindRoot(b);
    if (ra != rb) unionFindParent[ra] = rb;
}

int unionFindConnected(int a, int b) {
    return unionFindRoot(a) == unionFindRoot(b);
}

int main() {
    unionFindInit(6);
    unionFindMerge(0, 1);
    unionFindMerge(2, 3);
    unionFindMerge(1, 3);
    printf("0 与 3 连通: %s\\n", unionFindConnected(0, 3) ? "是" : "否");
    printf("0 与 5 连通: %s\\n", unionFindConnected(0, 5) ? "是" : "否");
    return 0;
}
`, variants: [
        { tpl: "unionFind", source: `#include <stdio.h>

void init(int parent[], int n) {
    for (int i = 0; i < n; i++) parent[i] = -1;
}

int Find(int parent[], int x) {
    if (parent[x] < 0) return x;
    return parent[x] = Find(parent, parent[x]);
}

void Union(int parent[], int x, int y) {
    int root1 = Find(parent, x);
    int root2 = Find(parent, y);
    if (root1 != root2) {
        if (parent[root1] < parent[root2]) {
            parent[root1] += parent[root2];
            parent[root2] = root1;
        } else {
            parent[root2] += parent[root1];
            parent[root1] = root2;
        }
    }
}

int main() {
    int parent[10];
    init(parent, 5);
    Union(parent, 0, 1);
    Union(parent, 2, 3);
    Union(parent, 1, 2);
    printf("%d\\n", Find(parent, 3));
    return 0;
}
` }
      ] },
      { id: "josephus", name: "约瑟夫环", template: "extra", source: `#include <stdio.h>

int josephus(int n, int m) {
    int r = 0;
    for (int i = 2; i <= n; i++) {
        r = (r + m) % i;
    }
    return r;
}

int main() {
    printf("n=5 m=3 最后幸存者编号: %d\\n", josephus(5, 3));
    printf("n=10 m=2 最后幸存者编号: %d\\n", josephus(10, 2));
    return 0;
}
`, variants: [
        { tpl: "josephus", source: `#include <stdio.h>
#define N 10

int main() {
    int alive[N];
    for (int i = 0; i < N; i++) alive[i] = 1;
    int count = 0, i = 0, remain = N;
    int m =  3;
    while (remain > 0) {
        if (alive[i]) {
            count++;
            if (count == m) {
                alive[i] = 0;
                printf("%d ", i);
                count = 0;
                remain--;
            }
        }
        i = (i + 1) % N;
    }
    printf("\\n");
    return 0;
}
` }
      ] },
    ] },
    { id: "string", label: "字符串", items: [
      { id: "string_match_bf", name: "朴素模式匹配", template: "stringMatchBF", source: `#include <stdio.h>
#include <string.h>

int indexBF(char S[], char T[], int pos) {
    int i = pos;
    int j = 0;
    int lenS = strlen(S);
    int lenT = strlen(T);
    while (i < lenS && j < lenT) {
        if (S[i] == T[j]) {
            i++;
            j++;
        } else {
            i = i - j + 1;
            j = 0;
        }
    }
    if (j >= lenT) return i - lenT;
    else return -1;
}

int main() {
    char S[] = "ababcabcacbab";
    char T[] = "abcac";
    int pos = indexBF(S, T, 0);
    printf("%d\\n", pos);
    return 0;
}
`, variants: [] },
      { id: "string_match_kmp", name: "KMP 模式匹配", template: "computeNextVal", source: `#include <stdio.h>
#include <string.h>

void getNext(char T[], int next[]) {
    int j = 0, k = -1;
    next[0] = -1;
    int lenT = strlen(T);
    while (j < lenT - 1) {
        if (k == -1 || T[j] == T[k]) {
            j++;
            k++;
            next[j] = k;
        } else {
            k = next[k];
        }
    }
}

void getNextVal(char T[], int nextval[]) {
    int next[20];
    getNext(T, next);
    int lenT = strlen(T);
    nextval[0] = -1;
    for (int j = 1; j < lenT; j++) {
        if (T[j] == T[next[j]])
            nextval[j] = nextval[next[j]];
        else
            nextval[j] = next[j];
    }
}

int main() {
    char T[] = "ababaaaba";
    int nextval[20];
    getNextVal(T, nextval);
    int lenT = strlen(T);
    for (int i = 0; i < lenT; i++)
        printf("%d ", nextval[i]);
    printf("\\n");
    return 0;
}
`, variants: [
        { tpl: "stringMatchKMP", source: `#include <stdio.h>
#include <string.h>

void getNext(char T[], int next[]) {
    int j = 0, k = -1;
    next[0] = -1;
    int lenT = strlen(T);
    while (j < lenT - 1) {
        if (k == -1 || T[j] == T[k]) {
            j++;
            k++;
            next[j] = k;
        } else {
            k = next[k];
        }
    }
}

int indexKMP(char S[], char T[], int pos) {
    int i = pos, j = 0;
    int next[20];
    getNext(T, next);
    int lenS = strlen(S);
    int lenT = strlen(T);
    while (i < lenS && j < lenT) {
        if (j == -1 || S[i] == T[j]) {
            i++;
            j++;
        } else {
            j = next[j];
        }
    }
    if (j >= lenT) return i - lenT;
    else return -1;
}

int main() {
    char S[] = "ababcabcacbab";
    char T[] = "abcac";
    int pos = indexKMP(S, T, 0);
    printf("%d\\n", pos);
    return 0;
}
` }
      ] },
      { id: "string_reverse", name: "字符串反转", template: "extra", source: `#include <stdio.h>
#include <string.h>

void reverseString(char s[]) {
    int len = strlen(s);
    for (int i = 0; i < len / 2; i++) {
        char t = s[i];
        s[i] = s[len - 1 - i];
        s[len - 1 - i] = t;
    }
}

int main() {
    char s[32] = "algorithm";
    reverseString(s);
    printf("%s\\n", s);
    return 0;
}
`, variants: [
        { tpl: "stringReverse", source: `#include <stdio.h>

int main() {
    char str[] = "hello";
    int len = 0;
    while (str[len] != '\\0') {
        len++;
    }
    for (int i = 0; i < len / 2; i++) {
        char temp = str[i];
        str[i] = str[len - i - 1];
        str[len - i - 1] = temp;
    }
    printf("%s\\n", str);
    return 0;
}
` }
      ] },
    ] },
    { id: "mathdp", label: "数学与动态规划", items: [
      { id: "gcd", name: "最大公约数", template: "gcd", source: `#include <stdio.h>

int gcd(int a, int b) {
    while (b != 0) {
        int temp = b;
        b = a % b;
        a = temp;
    }
    return a;
}

int main() {
    int a =  48, b =  18;
    printf("%d\\n", gcd(a, b));
    return 0;
}
`, variants: [] },
      { id: "hanoi", name: "汉诺塔", template: "hanoi", source: `#include <stdio.h>

void hanoi(int n, char from, char to, char aux) {
    if (n == 1) {
        printf("Move disk 1 from %c to %c\\n", from, to);
        return;
    }
    hanoi(n - 1, from, aux, to);
    printf("Move disk %d from %c to %c\\n", n, from, to);
    hanoi(n - 1, aux, to, from);
}

int main() {
    int n =  3;
    hanoi(n, 'A', 'C', 'B');
    return 0;
}
`, variants: [] },
      { id: "dp", name: "动态规划", template: "dpCoinChange", source: `#include <stdio.h>

int min(int a, int b) { return a < b ? a : b; }

int coinChange(int coins[], int coinCount, int amount) {
    int dp[101];
    for (int i = 0; i <= amount; i++) dp[i] = 100000;
    dp[0] = 0;
    for (int i = 0; i < coinCount; i++) {
        for (int j = coins[i]; j <= amount; j++) {
            dp[j] = min(dp[j], dp[j - coins[i]] + 1);
        }
    }
    if (dp[amount] == 100000) return -1;
    return dp[amount];
}

int main() {
    int coins[] = {1, 2, 5};
    int amount =  11;
    int result = coinChange(coins, 3, amount);
    printf("%d\\n", result);
    return 0;
}
`, variants: [
        { tpl: "dpFib", source: `#include <stdio.h>

int main() {
    int n =  10;
    int dp[20];
    dp[0] = 0;
    dp[1] = 1;
    for (int i = 2; i <= n; i++) {
        dp[i] = dp[i - 1] + dp[i - 2];
    }
    printf("%d\\n", dp[n]);
    return 0;
}
` }, 
        { tpl: "dpKnapsack", source: `#include <stdio.h>

int max(int a, int b) {
    return a > b ? a : b;
}

int main() {
    int W =  10;
    int wt[4] = {2, 3, 4, 5};
    int val[4] = {3, 4, 5, 6};
    int n = 4;
    int dp[5][15];
    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 15; j++) {
            dp[i][j] = 0;
        }
    }
    for (int i = 1; i <= n; i++) {
        for (int w = 1; w <= W; w++) {
            if (wt[i - 1] <= w) {
                dp[i][w] = max(val[i - 1] + dp[i - 1][w - wt[i - 1]], dp[i - 1][w]);
            } else {
                dp[i][w] = dp[i - 1][w];
            }
        }
    }
    printf("%d\\n", dp[n][W]);
    return 0;
}
` }, 
        { tpl: "dpLCS", source: `#include <stdio.h>
#include <string.h>

int max(int a, int b) { return a > b ? a : b; }

int lcs(char X[], char Y[]) {
    int m = strlen(X);
    int n = strlen(Y);
    int dp[20][20];
    for (int i = 0; i <= m; i++)
        for (int j = 0; j <= n; j++)
            dp[i][j] = 0;
    for (int i = 1; i <= m; i++) {
        for (int j = 1; j <= n; j++) {
            if (X[i - 1] == Y[j - 1])
                dp[i][j] = dp[i - 1][j - 1] + 1;
            else
                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1]);
        }
    }
    return dp[m][n];
}

int main() {
    char X[] = "ABCBDAB";
    char Y[] = "BDCABA";
    printf("%d\\n", lcs(X, Y));
    return 0;
}
` }, 
        { tpl: "dpLIS", source: `#include <stdio.h>

int max(int a, int b) { return a > b ? a : b; }

int lis(int arr[], int n) {
    int dp[20];
    for (int i = 0; i < n; i++) dp[i] = 1;
    int result = 1;
    for (int i = 1; i < n; i++) {
        for (int j = 0; j < i; j++) {
            if (arr[j] < arr[i])
                dp[i] = max(dp[i], dp[j] + 1);
        }
        result = max(result, dp[i]);
    }
    return result;
}

int main() {
    int arr[] = {10, 9, 2, 5, 3, 7, 101, 18};
    int n = 8;
    printf("%d\\n", lis(arr, n));
    return 0;
}
` }, 
        { tpl: "matrixChain", source: `#include <stdio.h>

int matrixChainOrder(int p[], int n) {
    int dp[10][10];
    for (int i = 0; i < n; i++)
        for (int j = 0; j < n; j++)
            dp[i][j] = 0;
    for (int len = 2; len < n; len++) {
        for (int i = 1; i < n - len + 1; i++) {
            int j = i + len - 1;
            dp[i][j] = 100000000;
            for (int k = i; k < j; k++) {
                int cost = dp[i][k] + dp[k + 1][j] + p[i - 1] * p[k] * p[j];
                if (cost < dp[i][j]) dp[i][j] = cost;
            }
        }
    }
    return dp[1][n - 1];
}

int main() {
    int p[] = {30, 35, 15, 5, 10, 20, 25};
    int n = 6;
    printf("%d\\n", matrixChainOrder(p, n + 1));
    return 0;
}
` }
      ] },
    ] },
    { id: "xlab", label: "扩展练习", xitems: [
      { id: "activitySelection", name: "activitySelection", source: `#include <stdio.h>

void selectActivities(int start[], int finish[], int n) {
    int i = 0;
    printf("%d ", i);
    for (int j = 1; j < n; j++) {
        if (start[j] >= finish[i]) {
            printf("%d ", j);
            i = j;
        }
    }
    printf("\\n");
}

int main() {
    int start[] = {1, 3, 0, 5, 8, 5};
    int finish[] = {2, 4, 6, 7, 9, 9};
    int n = 6;
    selectActivities(start, finish, n);
    return 0;
}
` },
      { id: "array", name: "array", source: `#include <stdio.h>

int main() {
    int arr[5] = {1, 2, 3, 4, 5};
    int sum = 0;
    for (int i = 0; i < 5; i++) {
        sum = sum + arr[i];
    }
    printf("%d\\n", sum);
    return 0;
}
` },
      { id: "bTree", name: "bTree", source: `#include <stdio.h>
#include <stdlib.h>
#define M 3

struct BTreeNode {
    int keys[M];
    struct BTreeNode* children[M + 1];
    int keyCount;
    int isLeaf;
};

struct BTreeNode* createNode(int isLeaf) {
    struct BTreeNode* node = (struct BTreeNode*)malloc(sizeof(struct BTreeNode));
    node->keyCount = 0;
    node->isLeaf = isLeaf;
    for (int i = 0; i <= M; i++) node->children[i] = NULL;
    return node;
}

void traverse(struct BTreeNode* root) {
    if (root) {
        int i;
        for (i = 0; i < root->keyCount; i++) {
            if (!root->isLeaf) traverse(root->children[i]);
            printf("%d ", root->keys[i]);
        }
        if (!root->isLeaf) traverse(root->children[i]);
    }
}

int search(struct BTreeNode* root, int key) {
    int i = 0;
    while (i < root->keyCount && key > root->keys[i]) i++;
    if (i < root->keyCount && key == root->keys[i]) return 1;
    if (root->isLeaf) return 0;
    return search(root->children[i], key);
}

void splitChild(struct BTreeNode* parent, int i, struct BTreeNode* child) {
    struct BTreeNode* newNode = createNode(child->isLeaf);
    newNode->keyCount = M / 2;
    for (int j = 0; j < M / 2; j++)
        newNode->keys[j] = child->keys[j + M / 2 + 1];
    if (!child->isLeaf) {
        for (int j = 0; j <= M / 2; j++)
            newNode->children[j] = child->children[j + M / 2 + 1];
    }
    child->keyCount = M / 2;
    for (int j = parent->keyCount; j >= i + 1; j--)
        parent->children[j + 1] = parent->children[j];
    parent->children[i + 1] = newNode;
    for (int j = parent->keyCount - 1; j >= i; j--)
        parent->keys[j + 1] = parent->keys[j];
    parent->keys[i] = child->keys[M / 2];
    parent->keyCount++;
}

void insertNonFull(struct BTreeNode* node, int key) {
    int i = node->keyCount - 1;
    if (node->isLeaf) {
        while (i >= 0 && key < node->keys[i]) {
            node->keys[i + 1] = node->keys[i];
            i--;
        }
        node->keys[i + 1] = key;
        node->keyCount++;
    } else {
        while (i >= 0 && key < node->keys[i]) i--;
        i++;
        if (node->children[i]->keyCount == M - 1) {
            splitChild(node, i, node->children[i]);
            if (key > node->keys[i]) i++;
        }
        insertNonFull(node->children[i], key);
    }
}

struct BTreeNode* insert(struct BTreeNode* root, int key) {
    if (!root) root = createNode(1);
    if (root->keyCount == M - 1) {
        struct BTreeNode* newRoot = createNode(0);
        newRoot->children[0] = root;
        splitChild(newRoot, 0, root);
        insertNonFull(newRoot, key);
        return newRoot;
    }
    insertNonFull(root, key);
    return root;
}

int main() {
    struct BTreeNode* root = NULL;
    root = insert(root, 10);
    root = insert(root, 20);
    root = insert(root, 5);
    root = insert(root, 6);
    root = insert(root, 12);
    root = insert(root, 30);
    root = insert(root, 7);
    root = insert(root, 17);
    printf("%d\\n", search(root, 6));
    traverse(root);
    printf("\\n");
    return 0;
}
` },
      { id: "bellmanFord", name: "bellmanFord", source: `#include <stdio.h>
#define MAXV 5
#define INF 65535

struct Edge {
    int u, v, w;
};

void BellmanFord(struct Edge edges[], int e, int n, int v0) {
    int dist[MAXV];
    for (int i = 0; i < n; i++) dist[i] = INF;
    dist[v0] = 0;
    for (int i = 1; i < n; i++) {
        for (int j = 0; j < e; j++) {
            int u = edges[j].u, v = edges[j].v, w = edges[j].w;
            if (dist[u] != INF && dist[u] + w < dist[v])
                dist[v] = dist[u] + w;
        }
    }
    for (int j = 0; j < e; j++) {
        int u = edges[j].u, v = edges[j].v, w = edges[j].w;
        if (dist[u] != INF && dist[u] + w < dist[v]) {
            printf("negative cycle\\n");
            return;
        }
    }
    for (int i = 0; i < n; i++) printf("%d ", dist[i]);
    printf("\\n");
}

int main() {
    struct Edge edges[] = {
        {0, 1, -1}, {0, 2, 4}, {1, 2, 3}, {1, 3, 2},
        {1, 4, 2}, {3, 2, 5}, {3, 1, 1}, {4, 3, -3}
    };
    BellmanFord(edges, 8, 5, 0);
    return 0;
}
` },
      { id: "bucketSort", name: "bucketSort", source: `#include <stdio.h>

void bucketSort(int arr[], int n) {
    int bucket[10][10];
    int count[10] = {0};
    int max = arr[0];
    for (int i = 1; i < n; i++)
        if (arr[i] > max) max = arr[i];
    for (int i = 0; i < n; i++) {
        int idx = (arr[i] * 10) / (max + 1);
        bucket[idx][count[idx]++] = arr[i];
    }
    for (int i = 0; i < 10; i++) {
        for (int j = 0; j < count[i] - 1; j++) {
            for (int k = 0; k < count[i] - j - 1; k++) {
                if (bucket[i][k] > bucket[i][k + 1]) {
                    int temp = bucket[i][k];
                    bucket[i][k] = bucket[i][k + 1];
                    bucket[i][k + 1] = temp;
                }
            }
        }
    }
    int idx = 0;
    for (int i = 0; i < 10; i++) {
        for (int j = 0; j < count[i]; j++)
            arr[idx++] = bucket[i][j];
    }
}

int main() {
    int arr[] = {29, 25, 3, 49, 9, 37, 21, 43};
    int n = 8;
    bucketSort(arr, n);
    for (int i = 0; i < n; i++)
        printf("%d ", arr[i]);
    printf("\\n");
    return 0;
}
` },
      { id: "criticalPath", name: "criticalPath", source: `#include <stdio.h>
#define MAXV 6
#define INF 65535

void CriticalPath(int G[][MAXV], int n) {
    int indegree[MAXV] = {0};
    int queue[MAXV];
    int front = 0, rear = 0;
    int ve[MAXV] = {0};
    int vl[MAXV];
    int topo[MAXV];
    int topoCount = 0;
    for (int i = 0; i < n; i++)
        for (int j = 0; j < n; j++)
            if (G[i][j] != INF && G[i][j] != 0) indegree[j]++;
    for (int i = 0; i < n; i++)
        if (indegree[i] == 0) queue[rear++] = i;
    while (front < rear) {
        int u = queue[front++];
        topo[topoCount++] = u;
        for (int v = 0; v < n; v++) {
            if (G[u][v] != INF && G[u][v] != 0) {
                if (ve[u] + G[u][v] > ve[v]) ve[v] = ve[u] + G[u][v];
                indegree[v]--;
                if (indegree[v] == 0) queue[rear++] = v;
            }
        }
    }
    for (int i = 0; i < n; i++) vl[i] = ve[topo[n - 1]];
    for (int i = n - 1; i >= 0; i--) {
        int u = topo[i];
        for (int v = 0; v < n; v++) {
            if (G[u][v] != INF && G[u][v] != 0) {
                if (vl[v] - G[u][v] < vl[u]) vl[u] = vl[v] - G[u][v];
            }
        }
    }
    for (int u = 0; u < n; u++) {
        for (int v = 0; v < n; v++) {
            if (G[u][v] != INF && G[u][v] != 0) {
                int e = ve[u];
                int l = vl[v] - G[u][v];
                if (e == l) printf("(%d,%d) ", u, v);
            }
        }
    }
    printf("\\n");
}

int main() {
    int G[MAXV][MAXV] = {
        {INF, 3, 2, INF, INF, INF},
        {INF, INF, INF, 2, 3, INF},
        {INF, INF, INF, 4, INF, 3},
        {INF, INF, INF, INF, INF, 2},
        {INF, INF, INF, INF, INF, 1},
        {INF, INF, INF, INF, INF, INF}
    };
    CriticalPath(G, MAXV);
    return 0;
}
` },
      { id: "deque", name: "deque", source: `#include <stdio.h>
#define MAXSIZE 10

struct Deque {
    int data[MAXSIZE];
    int front;
    int rear;
    int size;
};

void init(struct Deque* dq) {
    dq->front = 0;
    dq->rear = 0;
    dq->size = 0;
}

int isEmpty(struct Deque* dq) { return dq->size == 0; }
int isFull(struct Deque* dq) { return dq->size == MAXSIZE; }

void pushFront(struct Deque* dq, int x) {
    if (isFull(dq)) return;
    dq->front = (dq->front - 1 + MAXSIZE) % MAXSIZE;
    dq->data[dq->front] = x;
    dq->size++;
}

void pushRear(struct Deque* dq, int x) {
    if (isFull(dq)) return;
    dq->data[dq->rear] = x;
    dq->rear = (dq->rear + 1) % MAXSIZE;
    dq->size++;
}

int popFront(struct Deque* dq) {
    if (isEmpty(dq)) return -1;
    int x = dq->data[dq->front];
    dq->front = (dq->front + 1) % MAXSIZE;
    dq->size--;
    return x;
}

int popRear(struct Deque* dq) {
    if (isEmpty(dq)) return -1;
    dq->rear = (dq->rear - 1 + MAXSIZE) % MAXSIZE;
    int x = dq->data[dq->rear];
    dq->size--;
    return x;
}

int main() {
    struct Deque dq;
    init(&dq);
    pushRear(&dq, 10);
    pushRear(&dq, 20);
    pushFront(&dq, 5);
    printf("%d ", popFront(&dq));
    printf("%d ", popRear(&dq));
    printf("%d\\n", popFront(&dq));
    return 0;
}
` },
      { id: "doublyLinkedList", name: "doublyLinkedList", source: `#include <stdio.h>
#include <stdlib.h>

struct DNode {
    int data;
    struct DNode* prev;
    struct DNode* next;
};

struct DNode* createNode(int data) {
    struct DNode* node = (struct DNode*)malloc(sizeof(struct DNode));
    node->data = data;
    node->prev = NULL;
    node->next = NULL;
    return node;
}

struct DNode* append(struct DNode* head, int data) {
    struct DNode* newNode = createNode(data);
    if (head == NULL) return newNode;
    struct DNode* p = head;
    while (p->next != NULL) p = p->next;
    p->next = newNode;
    newNode->prev = p;
    return head;
}

void printForward(struct DNode* head) {
    struct DNode* p = head;
    while (p != NULL) {
        printf("%d ", p->data);
        p = p->next;
    }
    printf("\\n");
}

int main() {
    struct DNode* head = NULL;
    head = append(head, 1);
    head = append(head, 2);
    head = append(head, 3);
    printForward(head);
    return 0;
}
` },
      { id: "externalSort", name: "externalSort", source: `#include <stdio.h>
#define MAX 4

void replacementSelection(int arr[], int n) {
    int heap[MAX];
    int heapSize = n < MAX ? n : MAX;
    for (int i = 0; i < heapSize; i++) heap[i] = arr[i];
    int idx = heapSize;
    int output[30];
    int outCount = 0;
    while (heapSize > 0) {
        int minIdx = 0;
        for (int i = 1; i < heapSize; i++)
            if (heap[i] < heap[minIdx]) minIdx = i;
        output[outCount++] = heap[minIdx];
        if (idx < n) {
            int next = arr[idx++];
            if (next >= heap[minIdx])
                heap[minIdx] = next;
            else {
                heap[minIdx] = heap[heapSize - 1];
                heap[heapSize - 1] = next;
                heapSize--;
            }
        } else {
            heap[minIdx] = heap[heapSize - 1];
            heapSize--;
        }
    }
    for (int i = 0; i < outCount; i++)
        printf("%d ", output[i]);
    printf("\\n");
}

int main() {
    int arr[] = {51, 49, 39, 46, 38, 29, 14, 61, 15, 30, 1, 48, 52, 3, 63, 27, 4, 13, 89, 21, 53, 5, 34};
    int n = 23;
    replacementSelection(arr, n);
    return 0;
}
` },
      { id: "factorial", name: "factorial", source: `#include <stdio.h>

int factorial(int n) {
    if (n <= 1) return 1;
    return n * factorial(n - 1);
}

int main() {
    int result = factorial( 5);
    printf("%d\\n", result);
    return 0;
}
` },
      { id: "fib", name: "fib", source: `#include <stdio.h>

int fibonacci(int n) {
    if (n <= 1) return n;
    return fibonacci(n - 1) + fibonacci(n - 2);
}

int main() {
    int result = fibonacci( 7);
    printf("%d\\n", result);
    return 0;
}
` },
      { id: "fibonacciSearch", name: "fibonacciSearch", source: `#include <stdio.h>

int fib[20];

void initFib() {
    fib[0] = 0;
    fib[1] = 1;
    for (int i = 2; i < 20; i++)
        fib[i] = fib[i - 1] + fib[i - 2];
}

int fibonacciSearch(int arr[], int n, int key) {
    int k = 0;
    while (fib[k] < n + 1) k++;
    int temp[20];
    for (int i = 0; i < n; i++) temp[i] = arr[i];
    for (int i = n; i < fib[k]; i++) temp[i] = arr[n - 1];
    int low = 0, high = n - 1;
    while (low <= high) {
        int mid = low + fib[k - 1] - 1;
        if (key < temp[mid]) {
            high = mid - 1;
            k = k - 1;
        } else if (key > temp[mid]) {
            low = mid + 1;
            k = k - 2;
        } else {
            if (mid < n) return mid;
            else return n - 1;
        }
    }
    return -1;
}

int main() {
    initFib();
    int arr[] = {10, 20, 30, 40, 50, 60, 70, 80};
    int n = 8;
    int key =  30;
    int result = fibonacciSearch(arr, n, key);
    printf("%d\\n", result);
    return 0;
}
` },
      { id: "infixEvaluation", name: "infixEvaluation", source: `#include <stdio.h>
#include <ctype.h>
#define MAX 100

int opStack[MAX];
int opTop = -1;
int valStack[MAX];
int valTop = -1;

int precedence(char op) {
    if (op == '+' || op == '-') return 1;
    if (op == '*' || op == '/') return 2;
    return 0;
}

void pushOp(char c) { opStack[++opTop] = c; }
char popOp() { return opStack[opTop--]; }
void pushVal(int v) { valStack[++valTop] = v; }
int popVal() { return valStack[valTop--]; }

void applyOp() {
    char op = popOp();
    int b = popVal();
    int a = popVal();
    switch (op) {
        case '+': pushVal(a + b); break;
        case '-': pushVal(a - b); break;
        case '*': pushVal(a * b); break;
        case '/': pushVal(a / b); break;
    }
}

int evaluate(char expr[]) {
    int i = 0;
    while (expr[i] != '\\0') {
        if (expr[i] == ' ') {
            i++;
            continue;
        }
        if (isdigit(expr[i])) {
            int val = 0;
            while (isdigit(expr[i])) {
                val = val * 10 + (expr[i] - '0');
                i++;
            }
            pushVal(val);
            continue;
        }
        if (expr[i] == '(') {
            pushOp(expr[i]);
        } else if (expr[i] == ')') {
            while (opTop != -1 && opStack[opTop] != '(')
                applyOp();
            popOp();
        } else {
            while (opTop != -1 && precedence(opStack[opTop]) >= precedence(expr[i]))
                applyOp();
            pushOp(expr[i]);
        }
        i++;
    }
    while (opTop != -1)
        applyOp();
    return popVal();
}

int main() {
    char expr[] = "3 + 5 * 2 - 8 / 4";
    printf("%d\\n", evaluate(expr));
    return 0;
}
` },
      { id: "inorder", name: "inorder", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createTreeNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

void inorder(struct TreeNode* root) {
    if (root == NULL) return;
    inorder(root->left);
    printf("%d ", root->val);
    inorder(root->right);
}

int main() {
    struct TreeNode* root = createTreeNode(1);
    root->left = createTreeNode(2);
    root->right = createTreeNode(3);
    root->left->left = createTreeNode(4);
    root->left->right = createTreeNode(5);
    inorder(root);
    printf("\\n");
    return 0;
}
` },
      { id: "interpolationSearch", name: "interpolationSearch", source: `#include <stdio.h>

int interpolationSearch(int arr[], int n, int key) {
    int low = 0, high = n - 1;
    while (low <= high && key >= arr[low] && key <= arr[high]) {
        if (low == high) {
            if (arr[low] == key) return low;
            return -1;
        }
        int pos = low + (int)((double)(key - arr[low]) / (arr[high] - arr[low]) * (high - low));
        if (arr[pos] == key) return pos;
        if (arr[pos] < key) low = pos + 1;
        else high = pos - 1;
    }
    return -1;
}

int main() {
    int arr[] = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100};
    int n = 10;
    int key =  30;
    int result = interpolationSearch(arr, n, key);
    printf("%d\\n", result);
    return 0;
}
` },
      { id: "linear", name: "linear", source: `#include <stdio.h>

int linearSearch(int arr[], int n, int target) {
    for (int i = 0; i < n; i++) {
        if (arr[i] == target)
            return i;
    }
    return -1;
}

int main() {
    int arr[] = {10, 20, 30, 40, 50};
    int n = 5;
    int target =  30;
    int result = linearSearch(arr, n, target);
    printf("%d\\n", result);
    return 0;
}
` },
      { id: "linked", name: "linked", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* createNode(int data) {
    struct Node* newNode = (struct Node*)malloc(sizeof(struct Node));
    newNode->data = data;
    newNode->next = NULL;
    return newNode;
}

int main() {
    struct Node* head = createNode(1);
    head->next = createNode(2);
    head->next->next = createNode(3);
    printf("Head: %d\\n", head->data);
    return 0;
}
` },
      { id: "linkedDelete", name: "linkedDelete", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* createNode(int data) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node));
    node->data = data;
    node->next = NULL;
    return node;
}

struct Node* deleteNode(struct Node* head, int key) {
    struct Node* temp = head;
    struct Node* prev = NULL;
    if (temp != NULL && temp->data == key) {
        head = temp->next;
        free(temp);
        return head;
    }
    while (temp != NULL && temp->data != key) {
        prev = temp;
        temp = temp->next;
    }
    if (temp == NULL) return head;
    prev->next = temp->next;
    free(temp);
    return head;
}

void printList(struct Node* head) {
    struct Node* p = head;
    while (p != NULL) {
        printf("%d ", p->data);
        p = p->next;
    }
    printf("\\n");
}

int main() {
    struct Node* head = createNode(1);
    head->next = createNode(2);
    head->next->next = createNode(3);
    head = deleteNode(head, 2);
    printList(head);
    return 0;
}
` },
      { id: "linkedInsert", name: "linkedInsert", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* createNode(int data) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node));
    node->data = data;
    node->next = NULL;
    return node;
}

struct Node* insertFront(struct Node* head, int data) {
    struct Node* newNode = createNode(data);
    newNode->next = head;
    return newNode;
}

int main() {
    struct Node* head = NULL;
    head = insertFront(head, 3);
    head = insertFront(head, 2);
    head = insertFront(head, 1);
    printf("Head: %d\\n", head->data);
    return 0;
}
` },
      { id: "linkedListTail", name: "linkedListTail", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* createNode(int data) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node));
    node->data = data;
    node->next = NULL;
    return node;
}

struct Node* append(struct Node* head, int data) {
    struct Node* newNode = createNode(data);
    if (head == NULL) return newNode;
    struct Node* p = head;
    while (p->next != NULL) p = p->next;
    p->next = newNode;
    return head;
}

void printList(struct Node* head) {
    struct Node* p = head;
    while (p != NULL) {
        printf("%d ", p->data);
        p = p->next;
    }
    printf("\\n");
}

int main() {
    struct Node* head = NULL;
    head = append(head, 1);
    append(head, 2);
    append(head, 3);
    printList(head);
    return 0;
}
` },
      { id: "linkedTraverse", name: "linkedTraverse", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* createNode(int data) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node));
    node->data = data;
    node->next = NULL;
    return node;
}

void printList(struct Node* head) {
    struct Node* p = head;
    while (p != NULL) {
        printf("%d ", p->data);
        p = p->next;
    }
    printf("\\n");
}

int main() {
    struct Node* head = createNode(1);
    head->next = createNode(2);
    head->next->next = createNode(3);
    printList(head);
    return 0;
}
` },
      { id: "mergeSortedLists", name: "mergeSortedLists", source: `#include <stdio.h>
#include <stdlib.h>

struct Node {
    int data;
    struct Node* next;
};

struct Node* createNode(int data) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node));
    node->data = data;
    node->next = NULL;
    return node;
}

struct Node* merge(struct Node* L1, struct Node* L2) {
    struct Node dummy;
    struct Node* tail = &dummy;
    dummy.next = NULL;
    while (L1 != NULL && L2 != NULL) {
        if (L1->data <= L2->data) {
            tail->next = L1;
            L1 = L1->next;
        } else {
            tail->next = L2;
            L2 = L2->next;
        }
        tail = tail->next;
    }
    if (L1 != NULL) tail->next = L1;
    if (L2 != NULL) tail->next = L2;
    return dummy.next;
}

void printList(struct Node* head) {
    struct Node* p = head;
    while (p != NULL) {
        printf("%d ", p->data);
        p = p->next;
    }
    printf("\\n");
}

int main() {
    struct Node* L1 = createNode(1);
    L1->next = createNode(3);
    L1->next->next = createNode(5);
    struct Node* L2 = createNode(2);
    L2->next = createNode(4);
    L2->next->next = createNode(6);
    struct Node* L3 = merge(L1, L2);
    printList(L3);
    return 0;
}
` },
      { id: "parenthesesMatch", name: "parenthesesMatch", source: `#include <stdio.h>
#define MAX 100

int match(char expr[]) {
    char stack[MAX];
    int top = -1;
    for (int i = 0; expr[i] != '\\0'; i++) {
        if (expr[i] == '(' || expr[i] == '[' || expr[i] == '{') {
            stack[++top] = expr[i];
        } else if (expr[i] == ')' || expr[i] == ']' || expr[i] == '}') {
            if (top == -1) return 0;
            char left = stack[top--];
            if ((expr[i] == ')' && left != '(') ||
                (expr[i] == ']' && left != '[') ||
                (expr[i] == '}' && left != '{'))
                return 0;
        }
    }
    return top == -1;
}

int main() {
    char expr[] = "{[()]}";
    if (match(expr))
        printf("matched\\n");
    else
        printf("not matched\\n");
    return 0;
}
` },
      { id: "pointer", name: "pointer", source: `#include <stdio.h>

void swap(int* a, int* b) {
    int temp = *a;
    *a = *b;
    *b = temp;
}

int main() {
    int x = 3, y = 5;
    swap(&x, &y);
    printf("x=%d y=%d\\n", x, y);
    return 0;
}
` },
      { id: "polynomialAdd", name: "polynomialAdd", source: `#include <stdio.h>
#include <stdlib.h>

struct Term {
    int coef;
    int exp;
    struct Term* next;
};

struct Term* createTerm(int c, int e) {
    struct Term* node = (struct Term*)malloc(sizeof(struct Term));
    node->coef = c;
    node->exp = e;
    node->next = NULL;
    return node;
}

struct Term* addPoly(struct Term* pa, struct Term* pb) {
    struct Term dummy;
    struct Term* tail = &dummy;
    dummy.next = NULL;
    while (pa && pb) {
        if (pa->exp > pb->exp) {
            tail->next = createTerm(pa->coef, pa->exp);
            pa = pa->next;
        } else if (pa->exp < pb->exp) {
            tail->next = createTerm(pb->coef, pb->exp);
            pb = pb->next;
        } else {
            int sum = pa->coef + pb->coef;
            if (sum != 0)
                tail->next = createTerm(sum, pa->exp);
            pa = pa->next;
            pb = pb->next;
        }
        if (tail->next) tail = tail->next;
    }
    while (pa) {
        tail->next = createTerm(pa->coef, pa->exp);
        tail = tail->next; pa = pa->next;
    }
    while (pb) {
        tail->next = createTerm(pb->coef, pb->exp);
        tail = tail->next; pb = pb->next;
    }
    return dummy.next;
}

void printPoly(struct Term* p) {
    while (p) {
        printf("%dx^%d ", p->coef, p->exp);
        p = p->next;
    }
    printf("\\n");
}

int main() {
    struct Term* pa = createTerm(3, 3);
    pa->next = createTerm(2, 1);
    pa->next->next = createTerm(1, 0);
    struct Term* pb = createTerm(4, 3);
    pb->next = createTerm(-2, 1);
    struct Term* pc = addPoly(pa, pb);
    printPoly(pc);
    return 0;
}
` },
      { id: "postorder", name: "postorder", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createTreeNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

void postorder(struct TreeNode* root) {
    if (root == NULL) return;
    postorder(root->left);
    postorder(root->right);
    printf("%d ", root->val);
}

int main() {
    struct TreeNode* root = createTreeNode(1);
    root->left = createTreeNode(2);
    root->right = createTreeNode(3);
    root->left->left = createTreeNode(4);
    root->left->right = createTreeNode(5);
    postorder(root);
    printf("\\n");
    return 0;
}
` },
      { id: "queueArray", name: "queueArray", source: `#include <stdio.h>

int queue[100];
int front = 0, rear = 0;

void enqueue(int x) {
    queue[rear++] = x;
}

int dequeue() {
    if (front == rear) return -1;
    return queue[front++];
}

int main() {
    enqueue(10);
    enqueue(20);
    enqueue(30);
    printf("%d ", dequeue());
    printf("%d ", dequeue());
    printf("%d\\n", dequeue());
    return 0;
}
` },
      { id: "redBlackTree", name: "redBlackTree", source: `#include <stdio.h>
#include <stdlib.h>

enum Color { RED, BLACK };

struct RBNode {
    int data;
    enum Color color;
    struct RBNode* left;
    struct RBNode* right;
    struct RBNode* parent;
};

struct RBNode* createNode(int data) {
    struct RBNode* node = (struct RBNode*)malloc(sizeof(struct RBNode));
    node->data = data;
    node->color = RED;
    node->left = node->right = node->parent = NULL;
    return node;
}

struct RBNode* leftRotate(struct RBNode* root, struct RBNode* x) {
    struct RBNode* y = x->right;
    x->right = y->left;
    if (y->left) y->left->parent = x;
    y->parent = x->parent;
    if (!x->parent) root = y;
    else if (x == x->parent->left) x->parent->left = y;
    else x->parent->right = y;
    y->left = x;
    x->parent = y;
    return root;
}

struct RBNode* rightRotate(struct RBNode* root, struct RBNode* y) {
    struct RBNode* x = y->left;
    y->left = x->right;
    if (x->right) x->right->parent = y;
    x->parent = y->parent;
    if (!y->parent) root = x;
    else if (y == y->parent->left) y->parent->left = x;
    else y->parent->right = x;
    x->right = y;
    y->parent = x;
    return root;
}

struct RBNode* fixInsert(struct RBNode* root, struct RBNode* z) {
    while (z->parent && z->parent->color == RED) {
        if (z->parent == z->parent->parent->left) {
            struct RBNode* y = z->parent->parent->right;
            if (y && y->color == RED) {
                z->parent->color = BLACK;
                y->color = BLACK;
                z->parent->parent->color = RED;
                z = z->parent->parent;
            } else {
                if (z == z->parent->right) {
                    z = z->parent;
                    root = leftRotate(root, z);
                }
                z->parent->color = BLACK;
                z->parent->parent->color = RED;
                root = rightRotate(root, z->parent->parent);
            }
        } else {
            struct RBNode* y = z->parent->parent->left;
            if (y && y->color == RED) {
                z->parent->color = BLACK;
                y->color = BLACK;
                z->parent->parent->color = RED;
                z = z->parent->parent;
            } else {
                if (z == z->parent->left) {
                    z = z->parent;
                    root = rightRotate(root, z);
                }
                z->parent->color = BLACK;
                z->parent->parent->color = RED;
                root = leftRotate(root, z->parent->parent);
            }
        }
    }
    root->color = BLACK;
    return root;
}

struct RBNode* insert(struct RBNode* root, int data) {
    struct RBNode* z = createNode(data);
    struct RBNode* y = NULL;
    struct RBNode* x = root;
    while (x) {
        y = x;
        if (z->data < x->data) x = x->left;
        else x = x->right;
    }
    z->parent = y;
    if (!y) root = z;
    else if (z->data < y->data) y->left = z;
    else y->right = z;
    return fixInsert(root, z);
}

void inorder(struct RBNode* root) {
    if (root) {
        inorder(root->left);
        printf("%d ", root->data);
        inorder(root->right);
    }
}

int main() {
    struct RBNode* root = NULL;
    root = insert(root, 7);
    root = insert(root, 3);
    root = insert(root, 18);
    root = insert(root, 10);
    root = insert(root, 22);
    inorder(root);
    printf("\\n");
    return 0;
}
` },
      { id: "sieveOfEratosthenes", name: "sieveOfEratosthenes", source: `#include <stdio.h>
#define MAXN 50

void sieve(int n) {
    int isPrime[MAXN];
    for (int i = 0; i <= n; i++) isPrime[i] = 1;
    isPrime[0] = isPrime[1] = 0;
    for (int i = 2; i * i <= n; i++) {
        if (isPrime[i]) {
            for (int j = i * i; j <= n; j += i)
                isPrime[j] = 0;
        }
    }
    for (int i = 2; i <= n; i++)
        if (isPrime[i]) printf("%d ", i);
    printf("\\n");
}

int main() {
    int n =  30;
    sieve(n);
    return 0;
}
` },
      { id: "spfa", name: "spfa", source: `#include <stdio.h>
#define MAXV 5
#define INF 65535

struct Edge {
    int u, v, w;
};

void SPFA(struct Edge edges[], int e, int n, int v0) {
    int dist[MAXV];
    int inqueue[MAXV] = {0};
    // 队列容量上界：SPFA 普通队列（非循环）最坏每个节点入队 n 次
    //（负环检测在 count[v] > n 时终止，故上界 n*n）——固定 MAXV 会在
    // 特定输入下越界写 queue[MAXV]（E2E_FAILURES spfa_default 根因）
    int queue[MAXV * MAXV];
    int front = 0, rear = 0;
    int count[MAXV] = {0};
    for (int i = 0; i < n; i++) dist[i] = INF;
    dist[v0] = 0;
    queue[rear++] = v0;
    inqueue[v0] = 1;
    count[v0]++;
    while (front < rear) {
        int u = queue[front++];
        inqueue[u] = 0;
        for (int i = 0; i < e; i++) {
            if (edges[i].u == u) {
                int v = edges[i].v, w = edges[i].w;
                if (dist[u] + w < dist[v]) {
                    dist[v] = dist[u] + w;
                    if (!inqueue[v]) {
                        queue[rear++] = v;
                        inqueue[v] = 1;
                        count[v]++;
                        if (count[v] > n) {
                            printf("negative cycle\\n");
                            return;
                        }
                    }
                }
            }
        }
    }
    for (int i = 0; i < n; i++) printf("%d ", dist[i]);
    printf("\\n");
}

int main() {
    struct Edge edges[] = {
        {0, 1, -1}, {0, 2, 4}, {1, 2, 3}, {1, 3, 2},
        {1, 4, 2}, {3, 2, 5}, {3, 1, 1}, {4, 3, -3}
    };
    SPFA(edges, 8, 5, 0);
    return 0;
}
` },
      { id: "stackArray", name: "stackArray", source: `#include <stdio.h>

int stack[100];
int top = -1;

void push(int x) {
    stack[++top] = x;
}

int pop() {
    if (top < 0) return -1;
    return stack[top--];
}

int main() {
    push(10);
    push(20);
    push(30);
    printf("%d ", pop());
    printf("%d ", pop());
    printf("%d\\n", pop());
    return 0;
}
` },
      { id: "stringBasicOps", name: "stringBasicOps", source: `#include <stdio.h>
#include <string.h>

void strAssign(char T[], char chars[]) {
    int i = 0;
    while (chars[i] != '\\0') {
        T[i] = chars[i];
        i++;
    }
    T[i] = '\\0';
}

int strCompare(char S[], char T[]) {
    int i = 0;
    while (S[i] != '\\0' && T[i] != '\\0') {
        if (S[i] != T[i])
            return S[i] - T[i];
        i++;
    }
    return S[i] - T[i];
}

void subString(char Sub[], char S[], int pos, int len) {
    int j = 0;
    for (int i = pos; i < pos + len; i++) {
        Sub[j++] = S[i];
    }
    Sub[j] = '\\0';
}

void concat(char T[], char S1[], char S2[]) {
    int i = 0, j = 0;
    while (S1[i] != '\\0') {
        T[j++] = S1[i++];
    }
    i = 0;
    while (S2[i] != '\\0') {
        T[j++] = S2[i++];
    }
    T[j] = '\\0';
}

int main() {
    char s1[20], s2[20], sub[10], con[40];
    strAssign(s1, "hello");
    strAssign(s2, "world");
    printf("%d\\n", strCompare(s1, s2));
    subString(sub, s1, 1, 3);
    printf("%s\\n", sub);
    concat(con, s1, s2);
    printf("%s\\n", con);
    return 0;
}
` },
      { id: "treeNode", name: "treeNode", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createTreeNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

int main() {
    struct TreeNode* root = createTreeNode(1);
    root->left = createTreeNode(2);
    root->right = createTreeNode(3);
    printf("Root: %d\\n", root->val);
    return 0;
}
` },
      { id: "treePreorder", name: "treePreorder", source: `#include <stdio.h>
#include <stdlib.h>

struct TreeNode {
    int val;
    struct TreeNode* left;
    struct TreeNode* right;
};

struct TreeNode* createTreeNode(int val) {
    struct TreeNode* node = (struct TreeNode*)malloc(sizeof(struct TreeNode));
    node->val = val;
    node->left = NULL;
    node->right = NULL;
    return node;
}

void preorder(struct TreeNode* root) {
    if (root == NULL) return;
    printf("%d ", root->val);
    preorder(root->left);
    preorder(root->right);
}

int main() {
    struct TreeNode* root = createTreeNode(1);
    root->left = createTreeNode(2);
    root->right = createTreeNode(3);
    root->left->left = createTreeNode(4);
    root->left->right = createTreeNode(5);
    preorder(root);
    printf("\\n");
    return 0;
}
` },
      { id: "treeToForest", name: "treeToForest", source: `#include <stdio.h>
#include <stdlib.h>

struct CSNode {
    int data;
    struct CSNode* firstChild;
    struct CSNode* nextSibling;
};

struct CSNode* createNode(int data) {
    struct CSNode* node = (struct CSNode*)malloc(sizeof(struct CSNode));
    node->data = data;
    node->firstChild = NULL;
    node->nextSibling = NULL;
    return node;
}

void traverse(struct CSNode* root) {
    if (root == NULL) return;
    printf("%d ", root->data);
    traverse(root->firstChild);
    traverse(root->nextSibling);
}

int main() {
    struct CSNode* root = createNode(1);
    root->firstChild = createNode(2);
    root->firstChild->nextSibling = createNode(3);
    root->firstChild->nextSibling->nextSibling = createNode(4);
    root->firstChild->firstChild = createNode(5);
    traverse(root);
    printf("\\n");
    return 0;
}
` },
    ] },
  ],
};
