// Package jmemit：freeze digest → .json.mbt emitter（D-5 四变体 + 平面
// String 映射两形态）。机器写回域的 .mbt 真源生成器——freeze 循环：
// freeze-mb 写 .json（临时）→ emit 产 .json.mbt 真源 → jsonmbt build
// 再生 .json → round-trip 对拍 → 绿才入账。铺开批 2026-10-07（#47 批五）。
package jmemit

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Entry：vm_diff 四变体条目（键集漂移——D-5 tag 展开形态）。
type Entry struct {
	SrcSha    string `json:"src_sha"`
	ExitCode  int    `json:"exit_code"`
	StdoutSha string `json:"stdout_sha,omitempty"`
	MemorySha string `json:"memory_sha,omitempty"`
	KnownMB   string `json:"known_mb_digest,omitempty"`
	CompileF  bool   `json:"compile_fail,omitempty"`
}

// Flat：平面 String→String 映射（typeck/codegen/parser/lexer 四套 digest
// 的通用形态——name → 16hex）。
type Flat map[string]string

func w(b *strings.Builder, s string) { b.WriteString(s + "\n") }

// quote：MoonBit 字符串字面量（JSON 转义兼容——\" \\ \n 控制字符同规则）。
func Quote(s string) string {
	b, err := json.Marshal(s)
	if err != nil {
		panic(err) // string marshal 不可失败
	}
	return string(b)
}

// EmitVariants：四变体 digest → .json.mbt 文本（vm_diff 形态）。
// ord = 案例名的确定性序（调用方从原始 JSON 文本顺序抽取）。
func EmitVariants(version int, note string, ord []string, cases map[string]Entry) string {
	var b strings.Builder
	w(&b, "// @generated by vm_diff freeze (scripts/jmemit) —— 禁手改（再生成：freeze-mb 循环）。")
	w(&b, "pub struct Std {")
	w(&b, "  src_sha : String")
	w(&b, "  exit_code : Int")
	w(&b, "  stdout_sha : String")
	w(&b, "  memory_sha : String")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub struct CompileFail {")
	w(&b, "  src_sha : String")
	w(&b, "  exit_code : Int")
	w(&b, "  stdout_sha : String")
	w(&b, "  compile_fail : Bool")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub struct KnownDigest {")
	w(&b, "  src_sha : String")
	w(&b, "  exit_code : Int")
	w(&b, "  stdout_sha : String")
	w(&b, "  memory_sha : String")
	w(&b, "  known_mb_digest : String")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub struct FailKnown {")
	w(&b, "  src_sha : String")
	w(&b, "  exit_code : Int")
	w(&b, "  stdout_sha : String")
	w(&b, "  memory_sha : String")
	w(&b, "  compile_fail : Bool")
	w(&b, "}")
	w(&b, "")
	w(&b, "enum Case {")
	w(&b, "  Standard(Std)")
	w(&b, "  CompileFail(CompileFail)")
	w(&b, "  KnownDigest(KnownDigest)")
	w(&b, "  FailKnown(FailKnown)")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub struct Digest {")
	w(&b, "  version : Int")
	w(&b, "  note : String")
	w(&b, "  cases : Map[String, Case]")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub let golden_digest : Digest = Digest::{")
	fmt.Fprintf(&b, "  version: %d,\n", version)
	fmt.Fprintf(&b, "  note: %s,\n", Quote(note))
	w(&b, "  cases: {")
	for _, name := range ord {
		e, ok := cases[name]
		if !ok {
			continue
		}
		var line string
		switch {
		case e.CompileF && e.MemorySha == "" && e.KnownMB == "":
			line = fmt.Sprintf("    %s: CompileFail(CompileFail::{ src_sha: %s, exit_code: %d, stdout_sha: %s, compile_fail: true }),",
				Quote(name), Quote(e.SrcSha), e.ExitCode, Quote(e.StdoutSha))
		case e.CompileF && e.MemorySha != "":
			line = fmt.Sprintf("    %s: FailKnown(FailKnown::{ src_sha: %s, exit_code: %d, stdout_sha: %s, memory_sha: %s, compile_fail: true }),",
				Quote(name), Quote(e.SrcSha), e.ExitCode, Quote(e.StdoutSha), Quote(e.MemorySha))
		case e.KnownMB != "":
			line = fmt.Sprintf("    %s: KnownDigest(KnownDigest::{ src_sha: %s, exit_code: %d, stdout_sha: %s, memory_sha: %s, known_mb_digest: %s }),",
				Quote(name), Quote(e.SrcSha), e.ExitCode, Quote(e.StdoutSha), Quote(e.MemorySha), Quote(e.KnownMB))
		default:
			line = fmt.Sprintf("    %s: Standard(Std::{ src_sha: %s, exit_code: %d, stdout_sha: %s, memory_sha: %s }),",
				Quote(name), Quote(e.SrcSha), e.ExitCode, Quote(e.StdoutSha), Quote(e.MemorySha))
		}
		w(&b, line)
	}
	w(&b, "  },")
	w(&b, "}")
	return b.String()
}

// EmitFlat：平面 String→String digest → .json.mbt 文本（四差分驱动形态）。
// sections = 有序节（节名 → 案例 map）；ordOf = 每节案例确定性序。
func EmitFlat(version int, note string, sections []FlatSection) string {
	var b strings.Builder
	w(&b, "// @generated by freeze (scripts/jmemit) —— 禁手改（再生成：freeze 循环）。")
	w(&b, "pub struct Section {")
	w(&b, "  sources : Map[String, String]")
	w(&b, "  hashes : Map[String, String]")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub struct Digest {")
	w(&b, "  version : Int")
	w(&b, "  note : String")
	w(&b, "  sections : Map[String, Section]")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub let golden_digest : Digest = Digest::{")
	fmt.Fprintf(&b, "  version: %d,\n", version)
	fmt.Fprintf(&b, "  note: %s,\n", Quote(note))
	w(&b, "  sections: {")
	for i, sec := range sections {
		fmt.Fprintf(&b, "    %s: Section::{", Quote(sec.Name))
		w(&b, "      sources: {")
		for _, n := range sec.SrcOrder {
			fmt.Fprintf(&b, "        %s: %s,", Quote(n), Quote(sec.Sources[n]))
		}
		w(&b, "      },")
		w(&b, "      hashes: {")
		for _, n := range sec.HashOrder {
			fmt.Fprintf(&b, "        %s: %s,", Quote(n), Quote(sec.Hashes[n]))
		}
		w(&b, "      },")
		if i < len(sections)-1 {
			b.WriteString("    },\n")
		} else {
			b.WriteString("    },\n")
		}
	}
	w(&b, "  },")
	w(&b, "}")
	return b.String()
}

// FlatSection：EmitFlat 的单节。
type FlatSection struct {
	Name      string
	Sources   Flat
	SrcOrder  []string
	Hashes    Flat
	HashOrder []string
}

// OrderKeys：map 键的排序序（确定性兜底——优先用调用方提供的原文序）。
func OrderKeys(m Flat) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

// WriteFile：落盘（utf-8 / LF）。
func WriteFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

// EmitSections：通用「节×双 String Map」digest → .json.mbt（typeck/
// codegen/parser/lexer 四套通用形态——节内 sources+hashes 两 Map，值
// 恒 16hex 字符串）。sections 序 = 调用方给的确定性序。
func EmitSections(version int, note string, sections []FlatSection) string {
	var b strings.Builder
	w(&b, "// @generated by freeze (scripts/jmemit) —— 禁手改（再生成：freeze 循环）。")
	w(&b, "pub struct Section {")
	w(&b, "  sources : Map[String, String]")
	w(&b, "  hashes : Map[String, String]")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub struct Digest {")
	w(&b, "  version : Int")
	w(&b, "  note : String")
	w(&b, "  sections : Map[String, Section]")
	w(&b, "}")
	w(&b, "")
	w(&b, "pub let golden_digest : Digest = Digest::{")
	fmt.Fprintf(&b, "  version: %d,\n", version)
	fmt.Fprintf(&b, "  note: %s,\n", Quote(note))
	w(&b, "  sections: {")
	for idx, sec := range sections {
		fmt.Fprintf(&b, "    %s: Section::{", Quote(sec.Name))
		w(&b, "      sources: {")
		for _, n := range sec.SrcOrder {
			fmt.Fprintf(&b, "        %s: %s,", Quote(n), Quote(sec.Sources[n]))
		}
		w(&b, "      },")
		w(&b, "      hashes: {")
		for _, n := range sec.HashOrder {
			fmt.Fprintf(&b, "        %s: %s,", Quote(n), Quote(sec.Hashes[n]))
		}
		b.WriteString("      },\n")
		if idx < len(sections)-1 {
			b.WriteString("    },\n")
		} else {
			b.WriteString("    },\n")
		}
	}
	w(&b, "  },")
	w(&b, "}")
	return b.String()
}
